-- =============================================================================
-- 00_b_init_identity.sql
-- Esquema IDENTITY (gobernado por ms-identity)
-- Contiene: contactos, usuarios, sesiones, RBAC (roles/permisos), catálogo de
-- sistemas/módulos/funcionalidades y avatar del perfil.
--
-- No depende de core. core y el resto de esquemas referencian a identity.
-- =============================================================================

SET search_path TO public, identity;

-- 1. REFERENCIAS
CREATE TABLE identity.tipo_contacto (
    tipo_contacto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT
);

-- 2. IDENTIDAD Y PERFILES
CREATE TABLE identity.contacto (
    contacto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(80) NOT NULL,
    apellido_paterno VARCHAR(80),
    apellido_materno VARCHAR(80),
    direccion TEXT,
    celular VARCHAR(20),
    correo VARCHAR(255) UNIQUE,

    -- Identificación personal
    tipo_documento VARCHAR(20),              -- RUT, DNI, PASAPORTE
    numero_documento VARCHAR(30),
    pais_emision CHAR(2) DEFAULT 'CL',
    fecha_nacimiento DATE,

    redes_sociales JSONB DEFAULT '{}'::jsonb,
    tipo_contacto_id BIGINT REFERENCES identity.tipo_contacto(tipo_contacto_id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    activo BOOLEAN DEFAULT true,
    eliminado_at TIMESTAMPTZ,

    CONSTRAINT ck_contacto_tipo_documento
        CHECK (tipo_documento IN ('RUT', 'DNI', 'PASAPORTE') OR tipo_documento IS NULL),
    CONSTRAINT ck_contacto_doc_consistente
        CHECK (
            (tipo_documento IS NULL AND numero_documento IS NULL) OR
            (tipo_documento IS NOT NULL AND numero_documento IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_contacto_documento
ON identity.contacto (tipo_documento, numero_documento, pais_emision)
WHERE numero_documento IS NOT NULL;

CREATE TABLE identity.usuario (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    activo BOOLEAN DEFAULT true,
    contacto_id BIGINT UNIQUE NOT NULL REFERENCES identity.contacto(contacto_id) ON DELETE CASCADE,
    -- Verificación de correo tras el registro (antes en 15_init_email_verificacion.sql)
    email_verificado BOOLEAN NOT NULL DEFAULT false,
    email_verificado_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON COLUMN identity.usuario.email_verificado IS
    'true cuando el usuario confirmó su correo con el código de 6 dígitos.';

-- Avatar del perfil. La FK a media.media_assets se agrega en 07_init_media.sql
-- (media se crea después de identity y core).
CREATE TABLE identity.avatar_attachments (
    usuario_id UUID REFERENCES identity.usuario(usuario_uuid),
    media_id UUID,
    sort_order INT,
    PRIMARY KEY (usuario_id, media_id)
);

-- 3. CATÁLOGO DE SISTEMAS / MÓDULOS / FUNCIONALIDADES (microfrontends)
CREATE TABLE identity.sistema (
    sistema_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    path VARCHAR(100),
    descripcion TEXT,
    activo BOOLEAN DEFAULT true,
    icono VARCHAR(50) NULL
);

CREATE TABLE identity.modulo (
    modulo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    path VARCHAR(100),
    descripcion TEXT,
    activo BOOLEAN DEFAULT true,
    sistema_id BIGINT REFERENCES identity.sistema(sistema_id),
    icono VARCHAR(50) NULL
);

CREATE TABLE identity.funcionalidad (
    funcionalidad_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    path VARCHAR(150),
    modulo_id BIGINT NOT NULL REFERENCES identity.modulo(modulo_id),
    activo BOOLEAN DEFAULT true,
    icono VARCHAR(50) NULL
);

-- 4. CONTROL DE ACCESO (RBAC)
CREATE TABLE identity.rol (
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    codigo VARCHAR(30) UNIQUE NOT NULL,
    descripcion TEXT
);

-- El tipo no estaba definido en ningún script (el DDL original fallaba desde cero).
CREATE TYPE identity.permiso_tipo AS ENUM ('VIEW', 'CREATE', 'UPDATE', 'DELETE');

CREATE TABLE identity.permiso (
    permiso_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    per_nombre VARCHAR(100) NOT NULL,
    per_cod VARCHAR(50) UNIQUE NOT NULL,
    per_desc VARCHAR(50) UNIQUE NOT NULL,
    per_activo BOOLEAN DEFAULT true,
    permiso_tipo identity.permiso_tipo NULL
);

CREATE TABLE identity.rol_modulo_permiso (
    rol_id BIGINT NOT NULL REFERENCES identity.rol(rol_id),
    modulo_id BIGINT NOT NULL REFERENCES identity.modulo(modulo_id),
    permiso_id BIGINT NOT NULL REFERENCES identity.permiso(permiso_id),
    PRIMARY KEY (rol_id, modulo_id, permiso_id)
);

CREATE TABLE identity.usuario_rol (
    usuario_id BIGINT NOT NULL REFERENCES identity.usuario(usuario_id) ON DELETE CASCADE,
    rol_id BIGINT NOT NULL REFERENCES identity.rol(rol_id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, rol_id)
);

-- 5. SESIONES Y RECUPERACIÓN DE CONTRASEÑA
CREATE TABLE identity.auth_refresh_sessions (
    id BIGSERIAL PRIMARY KEY,
    session_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    device_type VARCHAR(30) NOT NULL,
    device_fingerprint VARCHAR(128),
    refresh_token_hash VARCHAR(255) NOT NULL,
    ip VARCHAR(64),
    user_agent TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    rotation_parent_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_auth_refresh_sessions_user
    FOREIGN KEY (user_id)
    REFERENCES identity.usuario (usuario_id)
    ON DELETE CASCADE
);

CREATE TABLE identity.password_reset_tokens (
    id BIGSERIAL PRIMARY KEY,
    token_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    email VARCHAR(100) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    ip_address VARCHAR(64),
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_password_reset_user
    FOREIGN KEY (user_id)
    REFERENCES identity.usuario (usuario_id)
    ON DELETE CASCADE
);

-- Índices
CREATE INDEX idx_password_reset_token_hash ON identity.password_reset_tokens (token_hash);
CREATE INDEX idx_password_reset_user_id ON identity.password_reset_tokens (user_id);
CREATE INDEX idx_password_reset_expires_at ON identity.password_reset_tokens (expires_at);
CREATE INDEX idx_password_reset_email ON identity.password_reset_tokens (email);

CREATE INDEX idx_auth_refresh_sessions_user_id ON identity.auth_refresh_sessions (user_id);
CREATE INDEX idx_auth_refresh_sessions_expires_at ON identity.auth_refresh_sessions (expires_at);
CREATE INDEX idx_auth_refresh_sessions_device_user ON identity.auth_refresh_sessions (device_type, user_id);
CREATE INDEX idx_auth_refresh_sessions_rotation_parent ON identity.auth_refresh_sessions (rotation_parent_id);
CREATE INDEX idx_auth_refresh_sessions_token_hash ON identity.auth_refresh_sessions (refresh_token_hash);

-- 6. TRIGGERS
CREATE OR REPLACE FUNCTION identity.tr_update_timestamp() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_contacto_ts
BEFORE UPDATE ON identity.contacto
FOR EACH ROW EXECUTE PROCEDURE identity.tr_update_timestamp();

CREATE TRIGGER update_usuario_ts
BEFORE UPDATE ON identity.usuario
FOR EACH ROW EXECUTE PROCEDURE identity.tr_update_timestamp();

-- 7. PERMISOS DE ESQUEMA
GRANT ALL PRIVILEGES ON SCHEMA identity TO desarrollo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA identity TO desarrollo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA identity TO desarrollo;
