-- =============================================================================
-- ERP Core (gobernado por ms-core)
-- Incluye: Organizaciones, Jerarquías de Grupo y Cuentas.
-- Identidad (usuario, contacto, RBAC, sistemas) vive en el esquema identity
-- (00_b_init_identity.sql); aquí solo se referencia.
-- =============================================================================


SET search_path TO public, identity, media, core, factura;



-- 3. ESTRUCTURA EMPRESARIAL
CREATE TABLE core.organizacion (
    organizacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    razon_social VARCHAR(255) NOT NULL,

    -- Clasificación
    tipo_organizacion VARCHAR(20) NOT NULL DEFAULT 'JURIDICA', -- JURIDICA | PERSONA_NATURAL

    -- Identificación tributaria (obligatoria para JURIDICA)
    rut VARCHAR(12),
    dv CHAR(1),

    giro TEXT,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT ck_organizacion_tipo
        CHECK (tipo_organizacion IN ('JURIDICA', 'PERSONA_NATURAL')),
    CONSTRAINT ck_organizacion_identificacion
        CHECK (
            (tipo_organizacion = 'JURIDICA' AND rut IS NOT NULL AND dv IS NOT NULL)
            OR (tipo_organizacion = 'PERSONA_NATURAL')
        ),
    UNIQUE(rut, dv)
);

ALTER TABLE core.organizacion 
ADD COLUMN tipo_participante varchar(30) DEFAULT 'CEDENTE'
CHECK (tipo_participante IN ('CEDENTE', 'FINANCIADORA'));

CREATE TABLE core.organizacion_attachments (
    organizacion_id UUID REFERENCES core.organizacion(organizacion_uuid),
    media_id UUID, -- FK a media.media_assets se agrega en 07_init_media.sql
    sort_order INT,
    PRIMARY KEY (organizacion_id, media_id)
);

-- Catálogo de tipos de dirección organizacional
CREATE TABLE core.tipo_direccion_organizacion (
    tipo_direccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) UNIQUE NOT NULL, -- TRIBUTARIA, CASA_MATRIZ, SUCURSAL, BODEGA, ATENCION
    nombre VARCHAR(80) NOT NULL
);

-- Direcciones por organización (N:1)
CREATE TABLE core.organizacion_direccion (
    organizacion_direccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT NOT NULL REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    tipo_direccion_id BIGINT NOT NULL REFERENCES core.tipo_direccion_organizacion(tipo_direccion_id),

    -- Dirección estructurada (mejor para reportes/impuestos)
    calle VARCHAR(150) NOT NULL,
    numero VARCHAR(20),
    depto_oficina VARCHAR(30),
    comuna VARCHAR(80),
    ciudad VARCHAR(80),
    region VARCHAR(80),
    codigo_postal VARCHAR(20),
    pais CHAR(2) NOT NULL DEFAULT 'CL',

    referencia TEXT,
    es_principal BOOLEAN DEFAULT false,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Relación N:N Organizaciones <-> Contactos
CREATE TABLE core.organizacion_contacto (
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    contacto_id BIGINT REFERENCES identity.contacto(contacto_id) ON DELETE CASCADE,
    cargo VARCHAR(100),
    es_principal BOOLEAN DEFAULT false,
    PRIMARY KEY (organizacion_id, contacto_id)
);

ALTER TABLE core.organizacion_contacto
ADD COLUMN tipo_relacion varchar(30) DEFAULT 'REFERENCIA'
CHECK (tipo_relacion IN (
    'REFERENCIA',       -- contacto general
    'PROVEEDOR',        -- proveedor de servicios
    'FACTURACION',      -- contacto para temas de factura
    'LEGAL',            -- representante legal
    'COMERCIAL'         -- ejecutivo comercial externo
));

-- 4. JERARQUÍAS Y GRUPOS DE TRABAJO
CREATE TABLE core.grupo_trabajo (
    grupo_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    lider_usuario_uuid UUID REFERENCES identity.usuario(usuario_uuid), -- Jefe del grupo
    organizacion_id UUID NOT NULL REFERENCES core.organizacion(organizacion_uuid) ON DELETE CASCADE,
    activo BOOLEAN DEFAULT true,
    grupo_metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE core.grupo_miembro (
    miembro_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    grupo_id UUID NOT NULL REFERENCES core.grupo_trabajo(grupo_id) ON DELETE CASCADE,
    usuario_uuid UUID NOT NULL REFERENCES identity.usuario(usuario_uuid) ON DELETE CASCADE,
    -- Recursividad: apunta a otro miembro del mismo grupo
    jefe_directo_id UUID REFERENCES core.grupo_miembro(miembro_id), 
    cargo_en_grupo VARCHAR(100),
    grupo_metadata JSONB DEFAULT '{}'::jsonb,
    fecha_ingreso TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    active BOOLEAN DEFAULT true,
    UNIQUE(grupo_id, usuario_uuid) -- Un usuario solo puede ser miembro una vez por grupo
);

-- Relación N:N Organizaciones <-> Sistemas
CREATE TABLE core.organizacion_sistema (
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    sistema_id BIGINT REFERENCES identity.sistema(sistema_id) ON DELETE CASCADE,
    fecha_activacion DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (organizacion_id, sistema_id)
);

-- 7. OPERACIONES Y SESIONES
CREATE TABLE core.cuenta_bancaria (
    cuenta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    nombre_titular VARCHAR(150) NOT NULL,
    rut_titular VARCHAR(20),
    banco VARCHAR(100) NOT NULL,
    numero VARCHAR(50) NOT NULL,
    correo_contacto VARCHAR(255)
);

-- 8. AUDITORÍA Y VALIDACIONES (TRIGGERS)
CREATE OR REPLACE FUNCTION core.tr_update_timestamp() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Evitar que un miembro sea su propio jefe
CREATE OR REPLACE FUNCTION core.check_jerarquia() RETURNS TRIGGER AS $$
BEGIN
    -- Caso raíz: si se intenta auto-referenciar, se normaliza a NULL.
    -- Esto permite el caso de "miembro único" sin romper la FK recursiva.
    IF NEW.jefe_directo_id = NEW.miembro_id THEN
        NEW.jefe_directo_id := NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Validar: solo una dirección TRIBUTARIA por organización
CREATE OR REPLACE FUNCTION core.tr_check_unica_direccion_tributaria()
RETURNS TRIGGER AS $$
DECLARE
    v_codigo VARCHAR(30);
BEGIN
    SELECT tdo.codigo
      INTO v_codigo
      FROM core.tipo_direccion_organizacion tdo
     WHERE tdo.tipo_direccion_id = NEW.tipo_direccion_id;

    -- Solo valida cuando la fila nueva/actualizada es TRIBUTARIA
    IF v_codigo = 'TRIBUTARIA' THEN
        IF EXISTS (
            SELECT 1
              FROM core.organizacion_direccion od
              JOIN core.tipo_direccion_organizacion t
                ON t.tipo_direccion_id = od.tipo_direccion_id
             WHERE od.organizacion_id = NEW.organizacion_id
               AND t.codigo = 'TRIBUTARIA'
               AND (
                    TG_OP = 'INSERT'
                    OR od.organizacion_direccion_id <> NEW.organizacion_direccion_id
               )
        ) THEN
            RAISE EXCEPTION 'La organización % ya tiene una dirección TRIBUTARIA', NEW.organizacion_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER update_organizacion_ts
BEFORE UPDATE ON core.organizacion
FOR EACH ROW EXECUTE PROCEDURE core.tr_update_timestamp();

CREATE TRIGGER update_organizacion_direccion_ts
BEFORE UPDATE ON core.organizacion_direccion
FOR EACH ROW EXECUTE PROCEDURE core.tr_update_timestamp();

CREATE TRIGGER tr_check_jerarquia BEFORE INSERT OR UPDATE ON core.grupo_miembro FOR EACH ROW EXECUTE PROCEDURE core.check_jerarquia();

CREATE UNIQUE INDEX uq_org_contacto_principal
ON core.organizacion_contacto (organizacion_id)
WHERE es_principal = true;

-- Solo una dirección principal por tipo dentro de la organización
CREATE UNIQUE INDEX uq_org_dir_principal_por_tipo
ON core.organizacion_direccion (organizacion_id, tipo_direccion_id)
WHERE es_principal = true;

CREATE TRIGGER tr_check_unica_direccion_tributaria
BEFORE INSERT OR UPDATE ON core.organizacion_direccion
FOR EACH ROW
EXECUTE PROCEDURE core.tr_check_unica_direccion_tributaria();

-- 9. PERMISOS DE ESQUEMA
GRANT ALL PRIVILEGES ON SCHEMA core TO desarrollo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO desarrollo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA core TO desarrollo;