-- =============================================================================
-- ERP Core - Versión Final Consolidada (17 Tablas)
-- Incluye: Seguridad, Organizaciones, Microfrontends y Jerarquías de Grupo
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS core;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. REFERENCIAS
CREATE TABLE core.tipo_contacto (
    tipo_contacto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT
);

-- 2. IDENTIDAD Y PERFILES
CREATE TABLE core.contacto (
    contacto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(80) NOT NULL,
    apellido_paterno VARCHAR(80),
    apellido_materno VARCHAR(80),
    direccion TEXT,
    celular VARCHAR(20),
    correo VARCHAR(255) UNIQUE,

    -- Identificación personal
    tipo_documento VARCHAR(20),              -- RUT, DNI, PASAPORTE
    numero_documento VARCHAR(30),
    pais_emision CHAR(2) DEFAULT 'CL',
    fecha_nacimiento DATE,

    redes_sociales JSONB DEFAULT '{}'::jsonb,
    logo_metadata JSONB DEFAULT '{}'::jsonb,
    tipo_contacto_id BIGINT REFERENCES core.tipo_contacto(tipo_contacto_id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    activo BOOLEAN DEFAULT true,
    eliminado_at TIMESTAMPTZ,

    CONSTRAINT ck_contacto_tipo_documento
        CHECK (tipo_documento IN ('RUT', 'DNI', 'PASAPORTE') OR tipo_documento IS NULL),
    CONSTRAINT ck_contacto_doc_consistente
        CHECK (
            (tipo_documento IS NULL AND numero_documento IS NULL) OR
            (tipo_documento IS NOT NULL AND numero_documento IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_contacto_documento
ON core.contacto (tipo_documento, numero_documento, pais_emision)
WHERE numero_documento IS NOT NULL;

CREATE TABLE core.usuario (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    activo BOOLEAN DEFAULT true,
    contacto_id BIGINT UNIQUE NOT NULL REFERENCES core.contacto(contacto_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. ESTRUCTURA EMPRESARIAL
CREATE TABLE core.organizacion (
    organizacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    razon_social VARCHAR(255) NOT NULL,

    -- Clasificación
    tipo_organizacion VARCHAR(20) NOT NULL DEFAULT 'JURIDICA', -- JURIDICA | PERSONA_NATURAL

    -- Identificación tributaria (obligatoria para JURIDICA)
    rut VARCHAR(12),
    dv CHAR(1),

    giro TEXT,
    logo_metadata JSONB DEFAULT '{}'::jsonb,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT ck_organizacion_tipo
        CHECK (tipo_organizacion IN ('JURIDICA', 'PERSONA_NATURAL')),
    CONSTRAINT ck_organizacion_identificacion
        CHECK (
            (tipo_organizacion = 'JURIDICA' AND rut IS NOT NULL AND dv IS NOT NULL)
            OR (tipo_organizacion = 'PERSONA_NATURAL')
        ),
    UNIQUE(rut, dv)
);

-- Catálogo de tipos de dirección organizacional
CREATE TABLE core.tipo_direccion_organizacion (
    tipo_direccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) UNIQUE NOT NULL, -- TRIBUTARIA, CASA_MATRIZ, SUCURSAL, BODEGA, ATENCION
    nombre VARCHAR(80) NOT NULL
);

-- Direcciones por organización (N:1)
CREATE TABLE core.organizacion_direccion (
    organizacion_direccion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT NOT NULL REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    tipo_direccion_id BIGINT NOT NULL REFERENCES core.tipo_direccion_organizacion(tipo_direccion_id),

    -- Dirección estructurada (mejor para reportes/impuestos)
    calle VARCHAR(150) NOT NULL,
    numero VARCHAR(20),
    depto_oficina VARCHAR(30),
    comuna VARCHAR(80),
    ciudad VARCHAR(80),
    region VARCHAR(80),
    codigo_postal VARCHAR(20),
    pais CHAR(2) NOT NULL DEFAULT 'CL',

    referencia TEXT,
    es_principal BOOLEAN DEFAULT false,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Relación N:N Organizaciones <-> Contactos
CREATE TABLE core.organizacion_contacto (
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    contacto_id BIGINT REFERENCES core.contacto(contacto_id) ON DELETE CASCADE,
    cargo VARCHAR(100),
    es_principal BOOLEAN DEFAULT false,
    PRIMARY KEY (organizacion_id, contacto_id)
);

-- 4. JERARQUÍAS Y GRUPOS DE TRABAJO
CREATE TABLE core.grupo_trabajo (
    grupo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    lider_usuario_id BIGINT REFERENCES core.usuario(usuario_id), -- Jefe del grupo
    organizacion_id BIGINT NOT NULL REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE core.grupo_miembro (
    miembro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id BIGINT NOT NULL REFERENCES core.grupo_trabajo(grupo_id) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES core.usuario(usuario_id) ON DELETE CASCADE,
    -- Recursividad: apunta a otro miembro del mismo grupo
    jefe_directo_id BIGINT REFERENCES core.grupo_miembro(miembro_id), 
    cargo_en_grupo VARCHAR(100),
    fecha_ingreso TIMESTAMPTZ DEFAULT now(),
    UNIQUE(grupo_id, usuario_id)
);

-- 5. INFRAESTRUCTURA DE MICROFRONTENDS (Software)
CREATE TABLE core.sistema (
    sistema_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    path VARCHAR(100),
    descripcion TEXT,
    activo BOOLEAN DEFAULT true
);

-- Relación N:N Organizaciones <-> Sistemas
CREATE TABLE core.organizacion_sistema (
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    sistema_id BIGINT REFERENCES core.sistema(sistema_id) ON DELETE CASCADE,
    fecha_activacion DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (organizacion_id, sistema_id)
);

CREATE TABLE core.modulo (
    modulo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    path VARCHAR(100),
    descripcion TEXT,
    activo BOOLEAN DEFAULT true,
    sistema_id BIGINT REFERENCES core.sistema(sistema_id)
);

CREATE TABLE core.funcionalidad (
    funcionalidad_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    path VARCHAR(150),
    modulo_id BIGINT NOT NULL REFERENCES core.modulo(modulo_id),
    activo BOOLEAN DEFAULT true
);

-- 6. CONTROL DE ACCESO (RBAC)
CREATE TABLE core.rol (
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    codigo VARCHAR(30) UNIQUE NOT NULL,
    descripcion TEXT
 );

CREATE TABLE core.permiso (
    permiso_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    per_nombre VARCHAR(100) NOT NULL,
    per_cod VARCHAR(50) UNIQUE NOT NULL,
    per_desc VARCHAR(50) UNIQUE NOT NULL,
    per_activo BOOLEAN DEFAULT true
);

CREATE TABLE core.rol_modulo_permiso (
    rol_id BIGINT NOT NULL REFERENCES core.rol(rol_id),
    modulo_id BIGINT NOT NULL REFERENCES core.modulo(modulo_id),
    permiso_id BIGINT NOT NULL REFERENCES core.permiso(permiso_id),
    PRIMARY KEY (rol_id, modulo_id, permiso_id)
);

CREATE TABLE core.usuario_rol (
    usuario_id BIGINT NOT NULL REFERENCES core.usuario(usuario_id) ON DELETE CASCADE,
    rol_id BIGINT NOT NULL REFERENCES core.rol(rol_id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, rol_id)
);

-- 7. OPERACIONES Y SESIONES
CREATE TABLE core.cuenta_bancaria (
    cuenta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    nombre_titular VARCHAR(150) NOT NULL,
    rut_titular VARCHAR(20),
    banco VARCHAR(100) NOT NULL,
    numero VARCHAR(50) NOT NULL,
    correo_contacto VARCHAR(255)
);

CREATE TABLE core.auth_refresh_sessions (
    id BIGSERIAL PRIMARY KEY,
    session_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    device_type VARCHAR(30) NOT NULL,
    device_fingerprint VARCHAR(128),
    refresh_token_hash VARCHAR(255) NOT NULL,
    ip VARCHAR(64),
    user_agent TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    rotation_parent_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_auth_refresh_sessions_user
    FOREIGN KEY (user_id)
    REFERENCES core.usuario (usuario_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS core.password_reset_tokens (
  id BIGSERIAL PRIMARY KEY,
  token_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  user_id BIGINT NOT NULL,
  email VARCHAR(100) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  ip_address VARCHAR(64),
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_password_reset_user
    FOREIGN KEY (user_id)
    REFERENCES core.usuario (usuario_id)
    ON DELETE CASCADE
);

-- Índices recomendados
CREATE INDEX IF NOT EXISTS idx_password_reset_token_hash ON core.password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_password_reset_user_id ON core.password_reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_expires_at ON core.password_reset_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_password_reset_email ON core.password_reset_tokens (email);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_sessions_user_id ON auth_refresh_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_refresh_sessions_expires_at ON auth_refresh_sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_refresh_sessions_device_user ON auth_refresh_sessions (device_type, user_id);
CREATE INDEX IF NOT EXISTS idx_auth_refresh_sessions_rotation_parent ON auth_refresh_sessions (rotation_parent_id);
CREATE INDEX IF NOT EXISTS idx_auth_refresh_sessions_token_hash ON auth_refresh_sessions (refresh_token_hash);


-- 8. AUDITORÍA Y VALIDACIONES (TRIGGERS)
CREATE OR REPLACE FUNCTION core.tr_update_timestamp() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Evitar que un miembro sea su propio jefe
CREATE OR REPLACE FUNCTION core.check_jerarquia() RETURNS TRIGGER AS $$
BEGIN IF NEW.jefe_directo_id = NEW.miembro_id THEN RAISE EXCEPTION 'Auto-jerarquía no permitida'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;

-- Validar: solo una dirección TRIBUTARIA por organización
CREATE OR REPLACE FUNCTION core.tr_check_unica_direccion_tributaria()
RETURNS TRIGGER AS $$
DECLARE
    v_codigo VARCHAR(30);
BEGIN
    SELECT tdo.codigo
      INTO v_codigo
      FROM core.tipo_direccion_organizacion tdo
     WHERE tdo.tipo_direccion_id = NEW.tipo_direccion_id;

    -- Solo valida cuando la fila nueva/actualizada es TRIBUTARIA
    IF v_codigo = 'TRIBUTARIA' THEN
        IF EXISTS (
            SELECT 1
              FROM core.organizacion_direccion od
              JOIN core.tipo_direccion_organizacion t
                ON t.tipo_direccion_id = od.tipo_direccion_id
             WHERE od.organizacion_id = NEW.organizacion_id
               AND t.codigo = 'TRIBUTARIA'
               AND (
                    TG_OP = 'INSERT'
                    OR od.organizacion_direccion_id <> NEW.organizacion_direccion_id
               )
        ) THEN
            RAISE EXCEPTION 'La organización % ya tiene una dirección TRIBUTARIA', NEW.organizacion_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER update_contacto_ts
BEFORE UPDATE ON core.contacto
FOR EACH ROW EXECUTE PROCEDURE core.tr_update_timestamp();

CREATE TRIGGER update_usuario_ts
BEFORE UPDATE ON core.usuario
FOR EACH ROW EXECUTE PROCEDURE core.tr_update_timestamp();

CREATE TRIGGER update_organizacion_ts
BEFORE UPDATE ON core.organizacion
FOR EACH ROW EXECUTE PROCEDURE core.tr_update_timestamp();

CREATE TRIGGER update_organizacion_direccion_ts
BEFORE UPDATE ON core.organizacion_direccion
FOR EACH ROW EXECUTE PROCEDURE core.tr_update_timestamp();

CREATE TRIGGER tr_check_jerarquia BEFORE INSERT OR UPDATE ON core.grupo_miembro FOR EACH ROW EXECUTE PROCEDURE core.check_jerarquia();

CREATE UNIQUE INDEX uq_org_contacto_principal
ON core.organizacion_contacto (organizacion_id)
WHERE es_principal = true;

-- Solo una dirección principal por tipo dentro de la organización
CREATE UNIQUE INDEX uq_org_dir_principal_por_tipo
ON core.organizacion_direccion (organizacion_id, tipo_direccion_id)
WHERE es_principal = true;

CREATE TRIGGER tr_check_unica_direccion_tributaria
BEFORE INSERT OR UPDATE ON core.organizacion_direccion
FOR EACH ROW
EXECUTE PROCEDURE core.tr_check_unica_direccion_tributaria();

-- 9. PERMISOS DE ESQUEMA
GRANT ALL PRIVILEGES ON SCHEMA core TO desarrollo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO desarrollo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA core TO desarrollo;