-- =============================================================================
-- ERP Core - Versión Final Consolidada (17 Tablas)
-- Incluye: Seguridad, Organizaciones, Microfrontends y Jerarquías de Grupo
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS core;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. REFERENCIAS
CREATE TABLE core.tipo_contacto (
    tipo_contacto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    descripcion TEXT
);

-- 2. IDENTIDAD Y PERFILES
CREATE TABLE core.contacto (
    contacto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    direccion TEXT,
    celular VARCHAR(20),
    correo VARCHAR(255) UNIQUE,
    redes_sociales JSONB DEFAULT '{}'::jsonb,
    avatar_data JSONB DEFAULT '{}'::jsonb,
    tipo_contacto_id BIGINT REFERENCES core.tipo_contacto(tipo_contacto_id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE core.usuario (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    activo BOOLEAN DEFAULT true,
    contacto_id BIGINT UNIQUE NOT NULL REFERENCES core.contacto(contacto_id) ON DELETE CASCADE,
    fecha_creacion TIMESTAMPTZ DEFAULT now(),
    fecha_actualizacion TIMESTAMPTZ DEFAULT now()
);

-- 3. ESTRUCTURA EMPRESARIAL
CREATE TABLE core.organizacion (
    organizacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    razon_social VARCHAR(255) NOT NULL,
    rut INTEGER NOT NULL,
    dv CHAR(1) NOT NULL,
    giro TEXT,
    logo_url TEXT,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(rut, dv)
);

-- Relación N:N Organizaciones <-> Contactos
CREATE TABLE core.organizacion_contacto (
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    contacto_id BIGINT REFERENCES core.contacto(contacto_id) ON DELETE CASCADE,
    cargo VARCHAR(100),
    es_principal BOOLEAN DEFAULT false,
    PRIMARY KEY (organizacion_id, contacto_id)
);

-- 4. JERARQUÍAS Y GRUPOS DE TRABAJO
CREATE TABLE core.grupo_trabajo (
    grupo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    lider_usuario_id BIGINT REFERENCES core.usuario(usuario_id), -- Jefe del grupo
    organizacion_id BIGINT NOT NULL REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE core.grupo_miembro (
    miembro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id BIGINT NOT NULL REFERENCES core.grupo_trabajo(grupo_id) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES core.usuario(usuario_id) ON DELETE CASCADE,
    -- Recursividad: apunta a otro miembro del mismo grupo
    jefe_directo_id BIGINT REFERENCES core.grupo_miembro(miembro_id), 
    cargo_en_grupo VARCHAR(100),
    fecha_ingreso TIMESTAMPTZ DEFAULT now(),
    UNIQUE(grupo_id, usuario_id)
);

-- 5. INFRAESTRUCTURA DE MICROFRONTENDS (Software)
CREATE TABLE core.sistema (
    sistema_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    path VARCHAR(100),
    descripcion TEXT,
    activo BOOLEAN DEFAULT true
);

-- Relación N:N Organizaciones <-> Sistemas
CREATE TABLE core.organizacion_sistema (
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    sistema_id BIGINT REFERENCES core.sistema(sistema_id) ON DELETE CASCADE,
    fecha_activacion DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (organizacion_id, sistema_id)
);

CREATE TABLE core.modulo (
    modulo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    path VARCHAR(100),
    descripcion TEXT,
    activo BOOLEAN DEFAULT true,
    sistema_id BIGINT REFERENCES core.sistema(sistema_id)
);

CREATE TABLE core.funcionalidad (
    funcionalidad_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    path VARCHAR(150),
    modulo_id BIGINT NOT NULL REFERENCES core.modulo(modulo_id),
    activo BOOLEAN DEFAULT true
);

-- 6. CONTROL DE ACCESO (RBAC)
CREATE TABLE core.rol (
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    codigo VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE core.permiso (
    permiso_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    per_nombre VARCHAR(100) NOT NULL,
    per_cod VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE core.rol_modulo_permiso (
    rol_id BIGINT NOT NULL REFERENCES core.rol(rol_id),
    modulo_id BIGINT NOT NULL REFERENCES core.modulo(modulo_id),
    permiso_id BIGINT NOT NULL REFERENCES core.permiso(permiso_id),
    PRIMARY KEY (rol_id, modulo_id, permiso_id)
);

CREATE TABLE core.usuario_rol (
    usuario_id BIGINT NOT NULL REFERENCES core.usuario(usuario_id) ON DELETE CASCADE,
    rol_id BIGINT NOT NULL REFERENCES core.rol(rol_id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, rol_id)
);

-- 7. OPERACIONES Y SESIONES
CREATE TABLE core.cuenta_bancaria (
    cuenta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    nombre_titular VARCHAR(150) NOT NULL,
    rut_titular VARCHAR(20),
    banco VARCHAR(100) NOT NULL,
    numero VARCHAR(50) NOT NULL,
    correo_contacto VARCHAR(255)
);

CREATE TABLE core.auth_refresh_sessions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES core.usuario(usuario_id) ON DELETE CASCADE,
    device_type VARCHAR(30) NOT NULL,
    refresh_token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 8. AUDITORÍA Y VALIDACIONES (TRIGGERS)
CREATE OR REPLACE FUNCTION core.tr_update_timestamp() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ LANGUAGE plpgsql;

CREATE TRIGGER update_contacto_ts BEFORE UPDATE ON core.contacto FOR EACH ROW EXECUTE PROCEDURE core.tr_update_timestamp();

-- Evitar que un miembro sea su propio jefe
CREATE OR REPLACE FUNCTION core.check_jerarquia() RETURNS TRIGGER AS $$
BEGIN IF NEW.jefe_directo_id = NEW.miembro_id THEN RAISE EXCEPTION 'Auto-jerarquía no permitida'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;

CREATE TRIGGER tr_check_jerarquia BEFORE INSERT OR UPDATE ON core.grupo_miembro FOR EACH ROW EXECUTE PROCEDURE core.check_jerarquia();

-- 9. PERMISOS DE ESQUEMA
GRANT ALL PRIVILEGES ON SCHEMA core TO desarrollo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO desarrollo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA core TO desarrollo;