-- DROP SCHEMA bodega;

CREATE SCHEMA bodega AUTHORIZATION desarrollo;

-- DROP SEQUENCE ajuste_inventario_id_seq;

CREATE SEQUENCE ajuste_inventario_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE costo_costo_id_seq;

CREATE SEQUENCE costo_costo_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE inventario_fisico_id_seq;

CREATE SEQUENCE inventario_fisico_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE item_item_id_seq;

CREATE SEQUENCE item_item_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE movimiento_id_seq;

CREATE SEQUENCE movimiento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tipo_movimiento_id_seq;

CREATE SEQUENCE tipo_movimiento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE ubicacion_id_seq;

CREATE SEQUENCE ubicacion_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- bodega.bodega definition

-- Drop table

-- DROP TABLE bodega;

CREATE TABLE bodega (
	bodega_id int8 NOT NULL,
	bodega_nombre varchar(255) NULL,
	ubicacion varchar(255) NULL,
	CONSTRAINT bodega_pkey PRIMARY KEY (bodega_id)
);


-- bodega.inventario_fisico definition

-- Drop table

-- DROP TABLE inventario_fisico;

CREATE TABLE inventario_fisico (
	fecha date NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	usuario_id int8 NULL,
	observaciones varchar(255) NULL,
	CONSTRAINT inventario_fisico_pkey PRIMARY KEY (id)
);


-- bodega.marca definition

-- Drop table

-- DROP TABLE marca;

CREATE TABLE marca (
	marca_id int8 NOT NULL,
	marca_desc varchar(50) NULL,
	marca_nombre varchar(50) NULL,
	CONSTRAINT marca_pkey PRIMARY KEY (marca_id)
);


-- bodega.size_item definition

-- Drop table

-- DROP TABLE size_item;

CREATE TABLE size_item (
	size_id int8 NOT NULL,
	size_orden int8 NULL,
	"size" varchar(255) NULL,
	CONSTRAINT size_item_pkey PRIMARY KEY (size_id)
);


-- bodega.tipo definition

-- Drop table

-- DROP TABLE tipo;

CREATE TABLE tipo (
	tipo_id int8 NOT NULL,
	tipo_nombre varchar(20) NULL,
	tipo_desc varchar(50) NULL,
	CONSTRAINT tipo_pkey PRIMARY KEY (tipo_id)
);


-- bodega.tipo_movimiento definition

-- Drop table

-- DROP TABLE tipo_movimiento;

CREATE TABLE tipo_movimiento (
	afecta_stock bool NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar(255) NOT NULL,
	CONSTRAINT tipo_movimiento_nombre_key UNIQUE (nombre),
	CONSTRAINT tipo_movimiento_pkey PRIMARY KEY (id)
);


-- bodega.categoria definition

-- Drop table

-- DROP TABLE categoria;

CREATE TABLE categoria (
	cat_id int8 NOT NULL,
	tipo_id int8 NULL,
	cat_desc varchar(50) NULL,
	cat_nombre varchar(50) NULL,
	CONSTRAINT categoria_pkey PRIMARY KEY (cat_id),
	CONSTRAINT fkrxer990gbpclxtqcopdowudmf FOREIGN KEY (tipo_id) REFERENCES tipo(tipo_id)
);


-- bodega.size_tipo definition

-- Drop table

-- DROP TABLE size_tipo;

CREATE TABLE size_tipo (
	size_id int8 NOT NULL,
	tipo_id int8 NOT NULL,
	CONSTRAINT fk6npc7ewv3q52i7hmre1ajtda FOREIGN KEY (size_id) REFERENCES size_item(size_id),
	CONSTRAINT fk7dotxatcajmoo4373p6ekjytt FOREIGN KEY (tipo_id) REFERENCES tipo(tipo_id)
);


-- bodega.sub_categoria definition

-- Drop table

-- DROP TABLE sub_categoria;

CREATE TABLE sub_categoria (
	cat_id int8 NULL,
	sub_cat_id int8 NOT NULL,
	sub_cat_desc varchar(50) NULL,
	sub_cat_nombre varchar(50) NULL,
	CONSTRAINT sub_categoria_pkey PRIMARY KEY (sub_cat_id),
	CONSTRAINT fkr2bxiqsqceqjm99xx2ue856kl FOREIGN KEY (cat_id) REFERENCES categoria(cat_id)
);


-- bodega.ubicacion definition

-- Drop table

-- DROP TABLE ubicacion;

CREATE TABLE ubicacion (
	bodega_id int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	descripcion varchar(255) NULL,
	estante varchar(255) NULL,
	nombre varchar(255) NOT NULL,
	pasillo varchar(255) NULL,
	rack varchar(255) NULL,
	tipo varchar(255) NULL,
	CONSTRAINT ubicacion_pkey PRIMARY KEY (id),
	CONSTRAINT fknhqm6e2o1kp7mve0qc6vbuwkq FOREIGN KEY (bodega_id) REFERENCES bodega(bodega_id)
);


-- bodega.item definition

-- Drop table

-- DROP TABLE item;

CREATE TABLE item (
	item_sublimable bool NULL,
	cat_id int8 NULL,
	item_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	marca_id int8 NULL,
	org_id int8 NULL,
	size_id int8 NULL,
	sub_cat_id int8 NULL,
	tipo_id int8 NULL,
	item_nombre varchar(50) NULL,
	item_img_base64 varchar(255) NULL,
	CONSTRAINT item_pkey PRIMARY KEY (item_id),
	CONSTRAINT fk51h8kpdull9wpmccg1xs9c28f FOREIGN KEY (tipo_id) REFERENCES tipo(tipo_id),
	CONSTRAINT fk9qw7oqn9qp13p0ghsx72ks2ft FOREIGN KEY (sub_cat_id) REFERENCES sub_categoria(sub_cat_id),
	CONSTRAINT fkbroxxoj1t5akk2mhewwjhyhcl FOREIGN KEY (cat_id) REFERENCES categoria(cat_id),
	CONSTRAINT fkspewlei5sbnl8mr1ojmk685ja FOREIGN KEY (size_id) REFERENCES size_item(size_id),
	CONSTRAINT fksyodqhc72y05mpgpidsnmpfdv FOREIGN KEY (marca_id) REFERENCES marca(marca_id)
);


-- bodega.movimiento definition

-- Drop table

-- DROP TABLE movimiento;

CREATE TABLE movimiento (
	cantidad int4 NOT NULL,
	fecha timestamp(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	item_id int8 NOT NULL,
	tipo_movimiento_id int8 NOT NULL,
	ubicacion_destino_id int8 NULL,
	ubicacion_origen_id int8 NULL,
	usuario_id int8 NULL,
	motivo varchar(255) NULL,
	CONSTRAINT movimiento_pkey PRIMARY KEY (id),
	CONSTRAINT fk_movimiento_item FOREIGN KEY (item_id) REFERENCES item(item_id),
	CONSTRAINT fk_movimiento_tipo_movimiento FOREIGN KEY (tipo_movimiento_id) REFERENCES tipo_movimiento(id),
	CONSTRAINT fk_movimiento_ubicacion_destino FOREIGN KEY (ubicacion_destino_id) REFERENCES ubicacion(id),
	CONSTRAINT fk_movimiento_ubicacion_origen FOREIGN KEY (ubicacion_origen_id) REFERENCES ubicacion(id)
);


-- bodega.stock definition

-- Drop table

-- DROP TABLE stock;

CREATE TABLE stock (
	cantidad int4 NULL,
	item_id int4 NOT NULL,
	ubicacion_id int4 NOT NULL,
	CONSTRAINT stock_pkey PRIMARY KEY (item_id, ubicacion_id),
	CONSTRAINT fka07su6m65jdwx4fn4wcilnkqe FOREIGN KEY (ubicacion_id) REFERENCES ubicacion(id),
	CONSTRAINT fkf3gqo6e3aged60kygtbmtsd8s FOREIGN KEY (item_id) REFERENCES item(item_id)
);


-- bodega.ajuste_inventario definition

-- Drop table

-- DROP TABLE ajuste_inventario;

CREATE TABLE ajuste_inventario (
	diferencia int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	inventario_fisico_id int8 NULL,
	item_id int8 NULL,
	stock_actual int8 NOT NULL,
	stock_fisico int8 NOT NULL,
	ubicacion_id int8 NULL,
	CONSTRAINT ajuste_inventario_pkey PRIMARY KEY (id),
	CONSTRAINT fk1whc2trqsmfc9yjshmlaauylq FOREIGN KEY (item_id) REFERENCES item(item_id),
	CONSTRAINT fk3xj276s4g6mp1ehjatg7ct0bu FOREIGN KEY (ubicacion_id) REFERENCES ubicacion(id),
	CONSTRAINT fksi26o1flrixrqcdqf5osckrr8 FOREIGN KEY (inventario_fisico_id) REFERENCES inventario_fisico(id)
);


-- bodega.costo definition

-- Drop table

-- DROP TABLE costo;

CREATE TABLE costo (
	costo float8 NOT NULL,
	costo_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha_inicio timestamp(6) NOT NULL,
	fecha_termino timestamp(6) NULL,
	item_id int8 NOT NULL,
	CONSTRAINT costo_pkey PRIMARY KEY (costo_id),
	CONSTRAINT fkey6v007nxbcfd941n8ercpdjs FOREIGN KEY (item_id) REFERENCES item(item_id)
);