-- =============================================================================
-- ERP & B2B SOCIAL NETWORK - DDL CONSOLIDADO
-- Esquemas: core (Administración) y social (Marketplace/Red Social)
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS social;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- ESQUEMA SOCIAL: Feedback, Engagement y Visibilidad
-- -----------------------------------------------------------------------------

CREATE TABLE social.categoria_servicio (
    categoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT
);

-- Post de Trabajo con contadores denormalizados para performance de la Red Social
CREATE TABLE social.post_trabajo (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT NOT NULL REFERENCES core.organizacion(organizacion_id),
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT NOT NULL,
    categoria_id BIGINT REFERENCES social.categoria_servicio(categoria_id),
    multimedia_data JSONB DEFAULT '[]', -- [{url, type, order}]
    cliente_externo_id BIGINT REFERENCES core.organizacion(organizacion_id), 
    verificado BOOLEAN DEFAULT false,
    -- Contadores para el Feed
    count_likes INTEGER DEFAULT 0,
    count_comments INTEGER DEFAULT 0,
    count_shares INTEGER DEFAULT 0,
    promedio_calificacion NUMERIC(4,2) DEFAULT 0,
    fecha_posteo TIMESTAMPTZ DEFAULT now()
);

-- Cuestionario de Calificación
CREATE TABLE social.pregunta_calificacion (
    pregunta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto_pregunta TEXT NOT NULL,
    peso INTEGER DEFAULT 1
);

CREATE TABLE social.calificacion_trabajo (
    calificacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES social.post_trabajo(post_id) ON DELETE CASCADE,
    emisor_org_id BIGINT NOT NULL REFERENCES core.organizacion(organizacion_id),
    comentario_publico TEXT,
    puntaje_total NUMERIC(4,2),
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE social.calificacion_detalle (
    calificacion_id BIGINT REFERENCES social.calificacion_trabajo(calificacion_id),
    pregunta_id BIGINT REFERENCES social.pregunta_calificacion(pregunta_id),
    puntaje INTEGER CHECK (puntaje BETWEEN 1 AND 10),
    PRIMARY KEY (calificacion_id, pregunta_id)
);

-- Interacciones de Red Social
CREATE TABLE social.reaccion_post (
    post_id BIGINT REFERENCES social.post_trabajo(post_id) ON DELETE CASCADE,
    usuario_id BIGINT REFERENCES core.usuario(usuario_id),
    tipo_reaccion VARCHAR(20) DEFAULT 'LIKE',
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (post_id, usuario_id)
);

CREATE TABLE social.comentario_post (
    comentario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES social.post_trabajo(post_id) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES core.usuario(usuario_id),
    contenido TEXT NOT NULL,
    padre_id BIGINT REFERENCES social.comentario_post(comentario_id),
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE social.mencion_post (
    mencion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES social.post_trabajo(post_id),
    organizacion_mencionada_id BIGINT REFERENCES core.organizacion(organizacion_id),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- TRIGGERS: Lógica de Negocio y Contadores
-- -----------------------------------------------------------------------------

-- 1. Actualizar contador de likes automáticamente
CREATE OR REPLACE FUNCTION social.update_post_counters() RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE social.post_trabajo SET count_likes = count_likes + 1 WHERE post_id = NEW.post_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE social.post_trabajo SET count_likes = count_likes - 1 WHERE post_id = OLD.post_id;
    END IF;
    RETURN NULL;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER tr_update_likes AFTER INSERT OR DELETE ON social.reaccion_post
FOR EACH ROW EXECUTE PROCEDURE social.update_post_counters();

-- 2. Actualizar promedio de calificación cuando se valida un trabajo
CREATE OR REPLACE FUNCTION social.calc_promedio_post() RETURNS TRIGGER AS $$
BEGIN
    UPDATE social.post_trabajo 
    SET promedio_calificacion = (SELECT AVG(puntaje_total) FROM social.calificacion_trabajo WHERE post_id = NEW.post_id),
        verificado = true
    WHERE post_id = NEW.post_id;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER tr_update_score AFTER INSERT ON social.calificacion_trabajo
FOR EACH ROW EXECUTE PROCEDURE social.calc_promedio_post();