-- =============================================================================
-- 12_init_org_perfil.sql
-- Cuestionario de onboarding / perfil extendido de organización
-- Compatible con: CEDENTE, FINANCIADORA, BROKER
-- Alcance: multi-país (no solo Chile)
-- =============================================================================

SET search_path TO public, core;

-- ---------------------------------------------------------------------------
-- 1. CATÁLOGOS COMPARTIDOS
-- ---------------------------------------------------------------------------

-- Países (ISO 3166-1 alpha-2 + nombre para UI)
CREATE TABLE IF NOT EXISTS core.pais (
    pais_id   SERIAL          PRIMARY KEY,
    codigo    CHAR(2)         UNIQUE NOT NULL,   -- 'CL', 'PE', 'AR', 'MX' …
    nombre    VARCHAR(80)     NOT NULL,
    activo    BOOLEAN         DEFAULT true
);

-- Divisiones administrativas de nivel 1 (región, estado, provincia, departamento)
-- Genérico para cualquier país. "nivel_nombre" describe cómo se llama en ese país.
CREATE TABLE IF NOT EXISTS core.division_admin (
    division_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pais_id       INT            NOT NULL REFERENCES core.pais(pais_id),
    codigo        VARCHAR(10)    NOT NULL,            -- 'RM', 'BIO', 'LIM' …
    nombre        VARCHAR(120)   NOT NULL,
    nivel_nombre  VARCHAR(40)    NOT NULL DEFAULT 'Región', -- 'Región','Estado','Provincia'
    activo        BOOLEAN        DEFAULT true,
    UNIQUE (pais_id, codigo)
);

-- Catálogo de productos/servicios financieros que puede ofrecer una financiera
CREATE TABLE IF NOT EXISTS core.producto_financiero (
    producto_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR(40)    UNIQUE NOT NULL,
    nombre        VARCHAR(120)   NOT NULL,
    descripcion   TEXT,
    aplica_a      VARCHAR(20)[]  NOT NULL DEFAULT ARRAY['FINANCIADORA','BROKER'],
    activo        BOOLEAN        DEFAULT true
);

-- ---------------------------------------------------------------------------
-- 2. PERFIL EXTENDIDO DE ORGANIZACIÓN
--    Una fila por organización (1:1 con core.organizacion)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS core.organizacion_perfil (
    -- PK / FK
    organizacion_id         BIGINT  PRIMARY KEY
                            REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,

    -- ── Estado del cuestionario ──────────────────────────────────────────
    onboarding_completo     BOOLEAN         NOT NULL DEFAULT false,
    onboarding_completado_at TIMESTAMPTZ,

    -- ── Contrato digital ─────────────────────────────────────────────────
    -- NOTA: paises_operacion se DERIVA de organizacion_zona_operacion
    -- (ver vista v_organizacion_perfil_completo). No se almacena aquí
    -- para evitar inconsistencias. El wizard pobla las zonas directamente.
    tiene_contrato_digital  BOOLEAN         NOT NULL DEFAULT false,
    plataforma_firma        VARCHAR(80),            -- 'DocuSign','Mifiel','FirmaVirtual',…

    -- ── Tamaño / capacidad (relevante para FINANCIADORA) ─────────────────
    -- Monto mínimo por operación, en USD para normalizar entre monedas
    monto_min_usd           NUMERIC(18,2),
    -- Monto máximo por operación
    monto_max_usd           NUMERIC(18,2),
    -- Plazo típico de pago en días
    plazo_tipico_dias       INT,

    -- ── Datos de contacto de operaciones (centralizado aquí) ─────────────
    email_operaciones       VARCHAR(255),
    telefono_operaciones    VARCHAR(30),

    -- ── Preferencias de notificación ─────────────────────────────────────
    notif_email             BOOLEAN         NOT NULL DEFAULT true,
    notif_whatsapp          BOOLEAN         NOT NULL DEFAULT false,
    notif_sms               BOOLEAN         NOT NULL DEFAULT false,

    -- ── Campos adicionales libres (extensibilidad sin nueva migración) ────
    metadata                JSONB           NOT NULL DEFAULT '{}',

    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),

    CONSTRAINT ck_montos
        CHECK (monto_min_usd IS NULL OR monto_max_usd IS NULL
               OR monto_min_usd <= monto_max_usd)
);

-- ---------------------------------------------------------------------------
-- 3. ZONAS DE OPERACIÓN (N:N organización ↔ división administrativa)
--    Permite seleccionar regiones/estados concretos dentro de cada país.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS core.organizacion_zona_operacion (
    organizacion_id     BIGINT   NOT NULL REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    division_id         BIGINT   NOT NULL REFERENCES core.division_admin(division_id),
    es_principal        BOOLEAN  NOT NULL DEFAULT false,

    -- Trazabilidad: cómo se originó esta zona
    --   'DECLARADA'          → el usuario la marcó explícitamente en el wizard
    --   'DERIVADA_DIRECCION' → se auto-generó desde una dirección física
    origen              VARCHAR(25) NOT NULL DEFAULT 'DECLARADA'
                        CHECK (origen IN ('DECLARADA', 'DERIVADA_DIRECCION')),

    -- Cuando origen = 'DERIVADA_DIRECCION', traza a la dirección que la generó.
    -- ON DELETE SET NULL: si se elimina la dirección la zona PERSISTE
    -- (la org puede seguir operando allí aunque cierre esa sucursal).
    direccion_origen_id BIGINT   NULL
                        REFERENCES core.organizacion_direccion(organizacion_direccion_id)
                        ON DELETE SET NULL,

    PRIMARY KEY (organizacion_id, division_id)
);

COMMENT ON TABLE core.organizacion_zona_operacion IS
    'Cobertura operativa declarada por la organización. '
    'Una zona puede existir sin dirección física (campo declarado en el wizard) '
    'o derivarse automáticamente de una dirección vía trigger.';

-- ---------------------------------------------------------------------------
-- 4. PRODUCTOS QUE MANEJA LA ORGANIZACIÓN (N:N)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS core.organizacion_producto (
    organizacion_id  BIGINT  NOT NULL REFERENCES core.organizacion(organizacion_id)  ON DELETE CASCADE,
    producto_id      BIGINT  NOT NULL REFERENCES core.producto_financiero(producto_id),
    activo           BOOLEAN NOT NULL DEFAULT true,
    -- condiciones específicas de esta org para este producto (tasas, límites, etc.)
    condiciones      JSONB   NOT NULL DEFAULT '{}',
    PRIMARY KEY (organizacion_id, producto_id)
);

-- ---------------------------------------------------------------------------
-- 5. DATOS INICIALES (catálogos mínimos)
-- ---------------------------------------------------------------------------

-- Países (los más relevantes para el mercado latinoamericano + España)
INSERT INTO core.pais (codigo, nombre) VALUES
    ('CL', 'Chile'),
    ('AR', 'Argentina'),
    ('PE', 'Perú'),
    ('CO', 'Colombia'),
    ('MX', 'México'),
    ('EC', 'Ecuador'),
    ('UY', 'Uruguay'),
    ('BO', 'Bolivia'),
    ('PY', 'Paraguay'),
    ('VE', 'Venezuela'),
    ('BR', 'Brasil'),
    ('ES', 'España'),
    ('US', 'Estados Unidos')
ON CONFLICT (codigo) DO NOTHING;

-- Regiones de Chile (división_admin)
INSERT INTO core.division_admin (pais_id, codigo, nombre, nivel_nombre)
SELECT p.pais_id, d.codigo, d.nombre, 'Región'
FROM core.pais p,
(VALUES
    ('RM',  'Región Metropolitana de Santiago'),
    ('AN',  'Región de Antofagasta'),
    ('AR',  'Región de la Araucanía'),
    ('AT',  'Región de Atacama'),
    ('BI',  'Región del Biobío'),
    ('CO',  'Región de Coquimbo'),
    ('LR',  'Región de Los Ríos'),
    ('LL',  'Región de Los Lagos'),
    ('LB',  'Región de Aysén'),
    ('MA',  'Región de Magallanes'),
    ('ML',  'Región del Maule'),
    ('NB',  'Región de Ñuble'),
    ('OH',  'Región de O''Higgins'),
    ('TA',  'Región de Tarapacá'),
    ('AP',  'Región de Arica y Parinacota'),
    ('VS',  'Región de Valparaíso')
) AS d(codigo, nombre)
WHERE p.codigo = 'CL'
ON CONFLICT (pais_id, codigo) DO NOTHING;

-- Productos financieros base
INSERT INTO core.producto_financiero (codigo, nombre, descripcion, aplica_a) VALUES
    ('FACTORING_CONVENCIONAL',   'Factoring Convencional',    'Cesión de facturas al cobro a valor presente', ARRAY['FINANCIADORA','BROKER']),
    ('FACTORING_INTERNACIONAL',  'Factoring Internacional',   'Operaciones con facturas de exportación/importación', ARRAY['FINANCIADORA','BROKER']),
    ('CONFIRMING',               'Confirming',                'Pago anticipado a proveedores', ARRAY['FINANCIADORA']),
    ('REVERSE_FACTORING',        'Reverse Factoring',         'Financiamiento en cadena de suministro', ARRAY['FINANCIADORA']),
    ('LEASING',                  'Leasing',                   'Arrendamiento financiero de activos', ARRAY['FINANCIADORA']),
    ('CREDITO_DIRECTO',          'Crédito Directo',           'Préstamo corporativo sin garantía real', ARRAY['FINANCIADORA']),
    ('WARRANT',                  'Warrant',                   'Financiamiento con garantía de inventario', ARRAY['FINANCIADORA']),
    ('DESCUENTO_NOMINA',         'Descuento de Nómina',       'Anticipo sobre planilla de sueldos', ARRAY['FINANCIADORA']),
    ('CESION_CREDITOS',          'Cesión de Créditos',        'Venta de cartera de créditos', ARRAY['FINANCIADORA','BROKER']),
    ('INTERMEDIACION',           'Intermediación',            'Conexión entre cedentes y financieras', ARRAY['BROKER'])
ON CONFLICT (codigo) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. TRIGGER: actualizar updated_at automáticamente
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION core.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_organizacion_perfil_updated_at
    BEFORE UPDATE ON core.organizacion_perfil
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

-- ---------------------------------------------------------------------------
-- 7. VISTA RESUMEN (útil para el BFF y reportes)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW core.v_organizacion_perfil_completo AS
SELECT
    o.organizacion_id,
    o.organizacion_uuid,
    o.razon_social,
    o.tipo_participante,
    p.onboarding_completo,
    p.onboarding_completado_at,
    p.tiene_contrato_digital,
    p.plataforma_firma,
    p.monto_min_usd,
    p.monto_max_usd,
    p.plazo_tipico_dias,
    p.email_operaciones,
    p.notif_email,
    p.notif_whatsapp,
    p.notif_sms,

    -- Países de operación (DERIVADOS de las zonas, no almacenados)
    COALESCE(
        ARRAY_AGG(DISTINCT pai.codigo) FILTER (WHERE pai.codigo IS NOT NULL),
        '{}'
    ) AS paises_operacion,

    -- Zonas de operación: nombre de división + origen
    COALESCE(
        ARRAY_AGG(DISTINCT da.nombre) FILTER (WHERE da.nombre IS NOT NULL),
        '{}'
    ) AS zonas_operacion,

    -- Zonas declaradas manualmente (no derivadas de dirección)
    COALESCE(
        ARRAY_AGG(DISTINCT da.nombre)
            FILTER (WHERE da.nombre IS NOT NULL AND ozo.origen = 'DECLARADA'),
        '{}'
    ) AS zonas_declaradas,

    -- Productos activos (array de códigos)
    COALESCE(
        ARRAY_AGG(DISTINCT pf.codigo) FILTER (WHERE pf.codigo IS NOT NULL AND op.activo),
        '{}'
    ) AS productos_activos,

    p.metadata,
    p.updated_at AS perfil_actualizado_at

FROM core.organizacion o
LEFT JOIN core.organizacion_perfil          p   ON p.organizacion_id   = o.organizacion_id
LEFT JOIN core.organizacion_zona_operacion  ozo ON ozo.organizacion_id = o.organizacion_id
LEFT JOIN core.division_admin               da  ON da.division_id      = ozo.division_id
LEFT JOIN core.pais                         pai ON pai.pais_id         = da.pais_id
LEFT JOIN core.organizacion_producto        op  ON op.organizacion_id  = o.organizacion_id
LEFT JOIN core.producto_financiero          pf  ON pf.producto_id      = op.producto_id

GROUP BY
    o.organizacion_id, o.organizacion_uuid, o.razon_social, o.tipo_participante,
    p.onboarding_completo, p.onboarding_completado_at,
    p.tiene_contrato_digital, p.plataforma_firma,
    p.monto_min_usd, p.monto_max_usd, p.plazo_tipico_dias,
    p.email_operaciones, p.notif_email, p.notif_whatsapp, p.notif_sms,
    p.metadata, p.updated_at;

-- ---------------------------------------------------------------------------
-- 8. RELACIÓN organizacion_direccion ↔ division_admin
--    Vincula la dirección física de la org con el catálogo geográfico normalizado
--    y auto-sincroniza organizacion_zona_operacion via trigger.
-- ---------------------------------------------------------------------------

-- 8a. FK desde organizacion_direccion hacia division_admin (nullable).
--     Mantiene region/pais TEXT para backward-compat y para países sin catálogo cargado.
ALTER TABLE core.organizacion_direccion
    ADD COLUMN IF NOT EXISTS division_id BIGINT
        REFERENCES core.division_admin(division_id) ON DELETE SET NULL;

COMMENT ON COLUMN core.organizacion_direccion.division_id IS
    'FK al catálogo normalizado de divisiones administrativas. '
    'Cuando se informa, region y pais TEXT quedan como copia legible de respaldo.';

-- Índice para búsquedas por zona geográfica
CREATE INDEX IF NOT EXISTS idx_org_dir_division
    ON core.organizacion_direccion (division_id)
    WHERE division_id IS NOT NULL;

-- 8b. Trigger: al insertar / actualizar una dirección con division_id,
--     registra automáticamente la zona en organizacion_zona_operacion.
--     - INSERT:  si la fila nueva tiene division_id, garantiza la zona.
--     - UPDATE:  si cambia division_id, agrega la nueva zona (la antigua se deja
--                intacta porque la org puede seguir operando allí).
--     - DELETE:  no elimina la zona (puede haber otras direcciones en esa región).

CREATE OR REPLACE FUNCTION core.sync_zona_desde_direccion()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.division_id IS NOT NULL THEN
        INSERT INTO core.organizacion_zona_operacion
            (organizacion_id, division_id, es_principal, origen, direccion_origen_id)
        VALUES
            (NEW.organizacion_id, NEW.division_id, NEW.es_principal,
             'DERIVADA_DIRECCION', NEW.organizacion_direccion_id)
        ON CONFLICT (organizacion_id, division_id) DO UPDATE SET
            -- Promover a principal si la dirección lo indica
            es_principal        = EXCLUDED.es_principal
                                  OR core.organizacion_zona_operacion.es_principal,
            -- No sobreescribir la traza si el usuario ya la declaró manualmente
            direccion_origen_id = CASE
                WHEN core.organizacion_zona_operacion.origen = 'DECLARADA'
                    THEN core.organizacion_zona_operacion.direccion_origen_id
                ELSE EXCLUDED.direccion_origen_id
            END;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_sync_zona_desde_direccion
    AFTER INSERT OR UPDATE OF division_id, es_principal
    ON core.organizacion_direccion
    FOR EACH ROW EXECUTE FUNCTION core.sync_zona_desde_direccion();

-- 8c. Función auxiliar: poblar division_id en direcciones existentes
--     que ya tienen pais + region coincidentes con el catálogo.
--     Ejecutar manualmente una vez después de cargar la migración.
CREATE OR REPLACE FUNCTION core.backfill_division_en_direcciones()
RETURNS INTEGER LANGUAGE plpgsql AS $$
DECLARE
    filas_actualizadas INTEGER;
BEGIN
    UPDATE core.organizacion_direccion od
    SET division_id = da.division_id
    FROM core.division_admin da
    JOIN core.pais p ON p.pais_id = da.pais_id
    WHERE od.division_id IS NULL
      AND od.pais   = p.codigo
      AND (
          -- coincidencia exacta de nombre
          od.region = da.nombre
          -- o coincidencia de código (ej: 'RM' en el campo region)
          OR od.region = da.codigo
      );

    GET DIAGNOSTICS filas_actualizadas = ROW_COUNT;
    RETURN filas_actualizadas;
END;
$$;

COMMENT ON FUNCTION core.backfill_division_en_direcciones() IS
    'Rellena division_id en filas históricas de organizacion_direccion '
    'que tengan pais + region coincidentes con el catálogo. '
    'Retorna el número de filas actualizadas.';

-- ---------------------------------------------------------------------------
-- FIN 12_init_org_perfil.sql
-- ---------------------------------------------------------------------------
