-- =============================================================================
-- 13_init_credenciales_sii.sql
-- Almacenamiento seguro de credenciales SII por organización
--
-- ARQUITECTURA DE SEGURIDAD (dos capas):
--
--   Capa 1 — HashiCorp Vault (PRIMARIA, recomendada)
--     La clave SII vive en Vault bajo el path:
--       secret/data/sii/{organizacion_uuid}
--     La DB solo guarda la RUTA (vault_secret_path), nunca el valor.
--     NestJS lee el secreto de Vault en runtime con el token de servicio.
--
--   Capa 2 — pgcrypto AES-256 (FALLBACK / entornos sin Vault)
--     Si vault_secret_path es NULL, la clave se guarda cifrada en
--     clave_sii_enc (bytea). La clave de cifrado viene de la variable
--     de entorno SII_ENC_KEY inyectada por la aplicación — NUNCA
--     se almacena en la base de datos.
--
-- NUNCA almacenar la clave SII en texto plano.
-- NUNCA pasar SII_ENC_KEY como literal SQL en migraciones o seeds.
-- =============================================================================

SET search_path TO public, core;

-- ---------------------------------------------------------------------------
-- 1. TABLA DE CREDENCIALES SII
--    1:1 con core.organizacion (una org puede tener solo un set activo)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS core.organizacion_credencial_sii (

    -- PK / FK
    credencial_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id     BIGINT  NOT NULL UNIQUE
                        REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,

    -- ── Ambiente SII ────────────────────────────────────────────────────
    ambiente            VARCHAR(15) NOT NULL DEFAULT 'PRODUCCION'
                        CHECK (ambiente IN ('CERTIFICACION', 'PRODUCCION')),

    -- ── Identificador tributario (RUT de la empresa, sin guion) ─────────
    rut_empresa         VARCHAR(12) NOT NULL,

    -- ── CAPA 1: Referencia a Vault ───────────────────────────────────────
    -- Path en Vault KV donde vive la clave: secret/data/sii/{org_uuid}
    -- Si está poblado, clave_sii_enc debe ser NULL.
    vault_secret_path   TEXT,

    -- ── CAPA 2: Fallback cifrado con pgcrypto ────────────────────────────
    -- Cifrado: pgp_sym_encrypt(clave, SII_ENC_KEY) desde la aplicación.
    -- Si está poblado, vault_secret_path debe ser NULL.
    clave_sii_enc       BYTEA,

    -- ── Certificado digital (alternativa a clave) ────────────────────────
    -- Para orgs que autentican vía certificado digital en vez de clave.
    -- El certificado (.p12/.pfx) también vive en Vault.
    cert_vault_path     TEXT,

    -- ── Control de rotación ──────────────────────────────────────────────
    rotada_at           TIMESTAMPTZ,            -- Última vez que se cambió la clave
    vence_at            TIMESTAMPTZ,            -- Fecha de vencimiento del certificado
    ultimo_uso_at       TIMESTAMPTZ,            -- Último acceso exitoso al SII

    -- ── Estado ──────────────────────────────────────────────────────────
    activo              BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Solo puede haber una fuente activa: Vault XOR pgcrypto
    CONSTRAINT ck_credencial_fuente_exclusiva CHECK (
        (vault_secret_path IS NOT NULL AND clave_sii_enc IS NULL)
        OR (vault_secret_path IS NULL AND clave_sii_enc IS NOT NULL)
        OR (vault_secret_path IS NULL AND clave_sii_enc IS NULL) -- aún no configurada
    )
);

COMMENT ON TABLE core.organizacion_credencial_sii IS
    'Credenciales SII por organización. '
    'La clave nunca se almacena en texto plano: '
    'vive en HashiCorp Vault (vault_secret_path) '
    'o cifrada con AES-256 vía pgcrypto (clave_sii_enc). ';

COMMENT ON COLUMN core.organizacion_credencial_sii.vault_secret_path IS
    'Path en Vault KV donde se almacena la clave SII. '
    'Formato: secret/data/sii/{organizacion_uuid}. '
    'Si está poblado, clave_sii_enc debe ser NULL.';

COMMENT ON COLUMN core.organizacion_credencial_sii.clave_sii_enc IS
    'Clave SII cifrada con pgp_sym_encrypt(clave, SII_ENC_KEY). '
    'SII_ENC_KEY viene de variable de entorno — nunca se guarda en DB. '
    'Si está poblado, vault_secret_path debe ser NULL.';

-- ---------------------------------------------------------------------------
-- 2. AUDITORÍA DE ACCESOS (quién consultó la credencial y cuándo)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS core.credencial_sii_auditoria (
    auditoria_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credencial_id   BIGINT NOT NULL
                    REFERENCES core.organizacion_credencial_sii(credencial_id)
                    ON DELETE CASCADE,
    usuario_uuid    UUID   REFERENCES core.usuario(usuario_uuid) ON DELETE SET NULL,
    servicio        VARCHAR(50) NOT NULL,    -- 'ms-core', 'worker-storage', etc.
    operacion       VARCHAR(30) NOT NULL,    -- 'READ', 'ROTATE', 'VALIDATE'
    resultado       VARCHAR(10) NOT NULL
                    CHECK (resultado IN ('OK', 'FAIL', 'EXPIRED')),
    ip_origen       INET,
    detalle         TEXT,                   -- Mensaje de error si resultado != OK
    ocurrido_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_credencial_auditoria_credencial
    ON core.credencial_sii_auditoria (credencial_id, ocurrido_at DESC);

COMMENT ON TABLE core.credencial_sii_auditoria IS
    'Registro de auditoría de cada acceso a la credencial SII. '
    'Permite detectar usos anómalos y cumplir con requerimientos de trazabilidad.';

-- ---------------------------------------------------------------------------
-- 3. TRIGGER updated_at
-- ---------------------------------------------------------------------------

-- core.set_updated_at() ya existe desde 12_init_org_perfil.sql
CREATE OR REPLACE TRIGGER trg_credencial_sii_updated_at
    BEFORE UPDATE ON core.organizacion_credencial_sii
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at();

-- ---------------------------------------------------------------------------
-- 4. FUNCIÓN: registrar auditoría desde la aplicación (llamada por NestJS)
--
-- Uso desde NestJS:
--   await dataSource.query(
--     `SELECT core.log_acceso_sii($1, $2, $3, $4, $5, $6)`,
--     [credencialId, usuarioUuid, 'ms-core', 'READ', 'OK', clientIp]
--   );
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION core.log_acceso_sii(
    p_credencial_id BIGINT,
    p_usuario_uuid  UUID,
    p_servicio      VARCHAR,
    p_operacion     VARCHAR,
    p_resultado     VARCHAR,
    p_ip_origen     INET DEFAULT NULL,
    p_detalle       TEXT DEFAULT NULL
)
RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO core.credencial_sii_auditoria
        (credencial_id, usuario_uuid, servicio, operacion, resultado, ip_origen, detalle)
    VALUES
        (p_credencial_id, p_usuario_uuid, p_servicio, p_operacion, p_resultado, p_ip_origen, p_detalle);

    -- Actualizar último uso exitoso
    IF p_resultado = 'OK' THEN
        UPDATE core.organizacion_credencial_sii
        SET ultimo_uso_at = now()
        WHERE credencial_id = p_credencial_id;
    END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- 5. VISTA: estado de credenciales (sin exponer datos sensibles)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW core.v_estado_credenciales_sii AS
SELECT
    o.organizacion_uuid,
    o.razon_social,
    c.ambiente,
    c.rut_empresa,

    -- Fuente activa (nunca el valor)
    CASE
        WHEN c.vault_secret_path IS NOT NULL THEN 'VAULT'
        WHEN c.clave_sii_enc     IS NOT NULL THEN 'PGCRYPTO'
        ELSE 'NO_CONFIGURADA'
    END AS fuente_credencial,

    -- Usa certificado digital?
    (c.cert_vault_path IS NOT NULL) AS tiene_certificado,

    c.rotada_at,
    c.vence_at,
    c.ultimo_uso_at,
    c.activo,

    -- Último acceso (join a auditoría)
    aud.resultado        AS ultimo_resultado,
    aud.ocurrido_at      AS ultimo_acceso_at

FROM core.organizacion o
JOIN core.organizacion_credencial_sii c ON c.organizacion_id = o.organizacion_id
LEFT JOIN LATERAL (
    SELECT resultado, ocurrido_at
    FROM core.credencial_sii_auditoria a
    WHERE a.credencial_id = c.credencial_id
    ORDER BY ocurrido_at DESC
    LIMIT 1
) aud ON true;

-- ---------------------------------------------------------------------------
-- FIN 13_init_credenciales_sii.sql
-- ---------------------------------------------------------------------------
