-- =============================================================================
-- 17_init_verificacion_tributaria.sql
-- Estado tributario y actividades económicas de organizaciones
--
-- DISEÑO MULTI-FUENTE Y MULTI-PAÍS:
--   La tabla no almacena datos específicos de ningún organismo (SII, AFIP,
--   SAT, DIAN). En su lugar:
--     - Campos normalizados (booleanos semánticos) extraídos de cualquier fuente
--     - Campo `fuente` identifica el organismo de origen
--     - Campo `raw_response JSONB` conserva la respuesta cruda completa
--       para re-procesamiento, auditoría o extracción de nuevos campos
--       sin alterar el esquema
--
-- FUENTES SOPORTADAS (campo fuente):
--   'SII'   → Chile      (api.sii.cl)
--   'AFIP'  → Argentina  (api.afip.gov.ar)
--   'SAT'   → México     (api.sat.gob.mx)
--   'DIAN'  → Colombia   (api.dian.gov.co)
--   ... cualquier valor VARCHAR(20) válido
--
-- DEPENDE DE: 01_init_core.sql (core.organizacion, core.pais)
-- =============================================================================

SET search_path TO public, core;

-- ============================================================================
-- TABLA 1: organizacion_verificacion_tributaria
-- Estado tributario normalizado — 1 fila activa por organización
-- ============================================================================

CREATE TABLE IF NOT EXISTS core.organizacion_verificacion_tributaria (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id             BIGINT  NOT NULL
                                REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    pais_id                     INT     NOT NULL
                                REFERENCES core.pais(pais_id),

    -- ── Identificación en el organismo tributario ────────────────────────
    -- Identificador fiscal en el país de origen (RUT, CUIT, RFC, NIT...)
    identificador_fiscal        VARCHAR(30) NOT NULL,

    -- Nombre registrado ante el organismo tributario
    razon_social_oficial        VARCHAR(255),

    -- ── Fuente del dato ──────────────────────────────────────────────────
    -- Organismo que emitió la verificación: 'SII', 'AFIP', 'SAT', 'DIAN'
    fuente                      VARCHAR(20) NOT NULL,

    -- ── Estado tributario (campos normalizados — universales) ────────────
    -- ¿Está registrado ante el organismo?
    registrado                  BOOLEAN NOT NULL DEFAULT false,
    -- ¿Ha iniciado actividades / está activo?
    activo                      BOOLEAN NOT NULL DEFAULT false,
    -- ¿Cumple sus obligaciones tributarias vigentes?
    cumple_obligacion           BOOLEAN NOT NULL DEFAULT false,
    -- ¿Está en primera categoría / régimen general?
    primera_categoria           BOOLEAN NOT NULL DEFAULT false,
    -- ¿Está habilitado para emitir documentos tributarios electrónicos?
    emisor_dte                  BOOLEAN NOT NULL DEFAULT false,
    -- ¿Tiene timbrado/autorización para emitir facturas electrónicas?
    tiene_factura_electronica   BOOLEAN NOT NULL DEFAULT false,

    -- Fecha de inicio de actividades (normalizada)
    fecha_inicio_actividades    DATE,

    -- ── Flags de riesgo (true = problema detectado) ──────────────────────
    -- Deudas previsionales (Ley 8102 CL / equivalente)
    tiene_deuda_previsional     BOOLEAN NOT NULL DEFAULT false,
    -- En proceso de quiebra / insolvencia
    tiene_quiebra               BOOLEAN NOT NULL DEFAULT false,
    -- Restricción de folios o documentos
    tiene_restriccion_folios    BOOLEAN NOT NULL DEFAULT false,
    -- Tiene al menos una alerta calificada como grave por el organismo
    tiene_alerta_grave          BOOLEAN NOT NULL DEFAULT false,
    -- Resumen textual de la última alerta relevante (para mostrar en UI)
    ultima_alerta_texto         TEXT,

    -- ── Respuesta cruda completa (no perder ningún dato) ─────────────────
    -- Permite re-procesar sin re-consultar el organismo.
    -- Permite extraer nuevos campos sin ALTER TABLE.
    raw_response                JSONB NOT NULL DEFAULT '{}',

    -- ── Control de vigencia ──────────────────────────────────────────────
    -- La verificación tiene una vigencia (datos del SII cambian).
    -- vigente_hasta se calcula en la vista como consultado_en + 30 días.
    consultado_en               TIMESTAMPTZ NOT NULL DEFAULT now(),
    activo_registro             BOOLEAN NOT NULL DEFAULT true,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Una verificación activa por organización (UNIQUE parcial)
    UNIQUE (organizacion_id)
);

COMMENT ON TABLE core.organizacion_verificacion_tributaria IS
    'Estado tributario normalizado de una organización consultado a su organismo '
    'fiscal (SII/AFIP/SAT/DIAN). '
    'raw_response conserva la respuesta cruda para auditoría y re-procesamiento. '
    'vigente_hasta = consultado_en + 30 días — re-consultar si está vencida.';

COMMENT ON COLUMN core.organizacion_verificacion_tributaria.fuente IS
    'Organismo tributario origen: SII (Chile), AFIP (Argentina), SAT (México), DIAN (Colombia)';

COMMENT ON COLUMN core.organizacion_verificacion_tributaria.raw_response IS
    'Respuesta JSON completa del organismo. No alterar el esquema para nuevos campos: '
    'usar raw_response->''campo'' en queries o agregar columnas generadas.';

CREATE INDEX IF NOT EXISTS idx_vt_organizacion
    ON core.organizacion_verificacion_tributaria (organizacion_id)
    WHERE activo_registro = true;

CREATE INDEX IF NOT EXISTS idx_vt_fuente_pais
    ON core.organizacion_verificacion_tributaria (fuente, pais_id);

-- Índice GIN para queries sobre el JSON crudo (ej: raw_response @> '{"conTegi":true}')
CREATE INDEX IF NOT EXISTS idx_vt_raw_gin
    ON core.organizacion_verificacion_tributaria USING GIN (raw_response);

-- Trigger updated_at
CREATE OR REPLACE FUNCTION core.set_updated_at_verificacion_tributaria()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_updated_at_verificacion_tributaria
    ON core.organizacion_verificacion_tributaria;

CREATE TRIGGER trg_updated_at_verificacion_tributaria
    BEFORE UPDATE ON core.organizacion_verificacion_tributaria
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at_verificacion_tributaria();

-- ============================================================================
-- TABLA 2: categoria_economica
-- Catálogo normalizado de actividades/giros económicos por fuente tributaria.
-- Cada entrada es ÚNICA por (fuente, codigo) — no depende de ninguna org.
-- Basada en CIIU Rev.4 (estándar ONU — usado por SII, AFIP, DIAN, SAT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS core.categoria_economica (

    -- PK compuesta: un código puede repetirse entre organismos distintos
    fuente              VARCHAR(20) NOT NULL,
    codigo              VARCHAR(20) NOT NULL,

    -- Descripción oficial entregada por el organismo
    descripcion         VARCHAR(255),

    -- Clasificación tributaria (1=Primera categoría, 2=Segunda, etc.)
    categoria_tributaria SMALLINT,

    -- ¿La actividad está afecta a IVA?
    afecto_iva          BOOLEAN,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (fuente, codigo)
);

COMMENT ON TABLE core.categoria_economica IS
    'Catálogo normalizado de actividades económicas/giros por fuente tributaria. '
    'Cada actividad es única por (fuente, codigo). '
    'Código basado en CIIU Rev.4 (ONU) o equivalente local del organismo.';

COMMENT ON COLUMN core.categoria_economica.fuente IS
    'Organismo tributario de origen: SII (Chile), AFIP (Argentina), SAT (México), DIAN (Colombia).';

COMMENT ON COLUMN core.categoria_economica.codigo IS
    'Código CIIU Rev.4 o código local del organismo fiscal. '
    'Identificador primario junto con fuente.';

COMMENT ON COLUMN core.categoria_economica.afecto_iva IS
    'true = la actividad está gravada con IVA según el organismo de origen. '
    'NULL = dato no disponible en la fuente.';

CREATE INDEX IF NOT EXISTS idx_ce_codigo
    ON core.categoria_economica (codigo);

-- Trigger updated_at
CREATE OR REPLACE FUNCTION core.set_updated_at_categoria_economica()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_updated_at_categoria_economica
    ON core.categoria_economica;

CREATE TRIGGER trg_updated_at_categoria_economica
    BEFORE UPDATE ON core.categoria_economica
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at_categoria_economica();

-- ============================================================================
-- TABLA 3: actividad_organizacion
-- Relación N:M entre organización y categoría económica.
-- Una organización puede tener múltiples giros/actividades vigentes.
-- ============================================================================

CREATE TABLE IF NOT EXISTS core.actividad_organizacion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- FK por UUID (identificador externo de la organización)
    organizacion_uuid   UUID    NOT NULL
                        REFERENCES core.organizacion(organizacion_uuid) ON DELETE CASCADE,

    -- FK compuesta al catálogo de actividades
    fuente              VARCHAR(20) NOT NULL,
    codigo              VARCHAR(20) NOT NULL,

    FOREIGN KEY (fuente, codigo)
        REFERENCES core.categoria_economica(fuente, codigo),

    -- Parámetros propios de la relación organización ↔ actividad
    fecha_inicio        DATE,
    es_principal        BOOLEAN     NOT NULL DEFAULT false,
    activo              BOOLEAN     NOT NULL DEFAULT true,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Una organización no puede tener el mismo giro duplicado por fuente
    UNIQUE (organizacion_uuid, fuente, codigo)
);

COMMENT ON TABLE core.actividad_organizacion IS
    'Asociación entre una organización y sus actividades económicas declaradas. '
    'Permite múltiples giros por organización. '
    'FK doble (fuente, codigo) hacia el catálogo core.categoria_economica.';

COMMENT ON COLUMN core.actividad_organizacion.es_principal IS
    'true = giro principal de la organización (el primero declarado ante el organismo).';

COMMENT ON COLUMN core.actividad_organizacion.fecha_inicio IS
    'Fecha en que la organización declaró este giro ante el organismo tributario.';

CREATE INDEX IF NOT EXISTS idx_ao_organizacion
    ON core.actividad_organizacion (organizacion_uuid)
    WHERE activo = true;

CREATE INDEX IF NOT EXISTS idx_ao_fuente_codigo
    ON core.actividad_organizacion (fuente, codigo);

-- ============================================================================
-- VISTA: v_verificacion_tributaria_vigente
-- Devuelve la verificación activa + resumen de actividades por organización.
-- Usada por el BFF para mostrar el perfil tributario en el wizard.
-- ============================================================================

CREATE OR REPLACE VIEW core.v_verificacion_tributaria_vigente AS
SELECT
    vt.id,
    vt.organizacion_id,
    org.organizacion_uuid,
    vt.identificador_fiscal,
    vt.razon_social_oficial,
    vt.fuente,
    p.codigo                    AS pais_codigo,
    p.nombre                    AS pais_nombre,
    -- Estado
    vt.registrado,
    vt.activo,
    vt.cumple_obligacion,
    vt.primera_categoria,
    vt.emisor_dte,
    vt.tiene_factura_electronica,
    vt.fecha_inicio_actividades,
    -- Riesgo
    vt.tiene_deuda_previsional,
    vt.tiene_quiebra,
    vt.tiene_restriccion_folios,
    vt.tiene_alerta_grave,
    vt.ultima_alerta_texto,
    -- Vigencia (calculada aquí — TIMESTAMPTZ+INTERVAL no es IMMUTABLE)
    vt.consultado_en,
    (vt.consultado_en + INTERVAL '30 days')         AS vigente_hasta,
    (now() > vt.consultado_en + INTERVAL '30 days') AS requiere_actualizacion,
    -- Actividades (array JSON para consumo directo en el frontend)
    -- Resuelve: actividad_organizacion → categoria_economica (catálogo)
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object(
            'codigo',               ce.codigo,
            'descripcion',          ce.descripcion,
            'afecto_iva',           ce.afecto_iva,
            'categoria_tributaria', ce.categoria_tributaria,
            'es_principal',         ao.es_principal,
            'fecha_inicio',         ao.fecha_inicio
        ) ORDER BY ao.es_principal DESC, ao.fecha_inicio)
        FROM core.actividad_organizacion ao
        JOIN core.categoria_economica ce
            ON ce.fuente = ao.fuente AND ce.codigo = ao.codigo
        WHERE ao.organizacion_uuid = org.organizacion_uuid
          AND ao.activo = true),
        '[]'::jsonb
    )                           AS actividades
FROM core.organizacion_verificacion_tributaria vt
JOIN core.pais         p   ON p.pais_id             = vt.pais_id
JOIN core.organizacion org ON org.organizacion_id   = vt.organizacion_id
WHERE vt.activo_registro = true;

-- ============================================================================
-- FIN 17_init_verificacion_tributaria.sql
-- ============================================================================
