-- =============================================================================
-- 17_init_verificacion_tributaria.sql
-- Estado tributario y actividades económicas de organizaciones
--
-- DISEÑO MULTI-FUENTE Y MULTI-PAÍS:
--   La tabla no almacena datos específicos de ningún organismo (SII, AFIP,
--   SAT, DIAN). En su lugar:
--     - Campos normalizados (booleanos semánticos) extraídos de cualquier fuente
--     - Campo `fuente` identifica el organismo de origen
--     - Campo `raw_response JSONB` conserva la respuesta cruda completa
--       para re-procesamiento, auditoría o extracción de nuevos campos
--       sin alterar el esquema
--
-- FUENTES SOPORTADAS (campo fuente):
--   'SII'   → Chile      (api.sii.cl)
--   'AFIP'  → Argentina  (api.afip.gov.ar)
--   'SAT'   → México     (api.sat.gob.mx)
--   'DIAN'  → Colombia   (api.dian.gov.co)
--   ... cualquier valor VARCHAR(20) válido
--
-- DEPENDE DE: 01_init_core.sql (core.organizacion, core.pais)
-- =============================================================================

SET search_path TO public, core;

-- ============================================================================
-- TABLA 1: organizacion_verificacion_tributaria
-- Estado tributario normalizado — 1 fila activa por organización
-- ============================================================================

CREATE TABLE IF NOT EXISTS core.organizacion_verificacion_tributaria (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id             BIGINT  NOT NULL
                                REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    pais_id                     INT     NOT NULL
                                REFERENCES core.pais(pais_id),

    -- ── Identificación en el organismo tributario ────────────────────────
    -- Identificador fiscal en el país de origen (RUT, CUIT, RFC, NIT...)
    identificador_fiscal        VARCHAR(30) NOT NULL,

    -- Nombre registrado ante el organismo tributario
    razon_social_oficial        VARCHAR(255),

    -- ── Fuente del dato ──────────────────────────────────────────────────
    -- Organismo que emitió la verificación: 'SII', 'AFIP', 'SAT', 'DIAN'
    fuente                      VARCHAR(20) NOT NULL,

    -- ── Estado tributario (campos normalizados — universales) ────────────
    -- ¿Está registrado ante el organismo?
    registrado                  BOOLEAN NOT NULL DEFAULT false,
    -- ¿Ha iniciado actividades / está activo?
    activo                      BOOLEAN NOT NULL DEFAULT false,
    -- ¿Cumple sus obligaciones tributarias vigentes?
    cumple_obligacion           BOOLEAN NOT NULL DEFAULT false,
    -- ¿Está en primera categoría / régimen general?
    primera_categoria           BOOLEAN NOT NULL DEFAULT false,
    -- ¿Está habilitado para emitir documentos tributarios electrónicos?
    emisor_dte                  BOOLEAN NOT NULL DEFAULT false,
    -- ¿Tiene timbrado/autorización para emitir facturas electrónicas?
    tiene_factura_electronica   BOOLEAN NOT NULL DEFAULT false,

    -- Fecha de inicio de actividades (normalizada)
    fecha_inicio_actividades    DATE,

    -- ── Flags de riesgo (true = problema detectado) ──────────────────────
    -- Deudas previsionales (Ley 8102 CL / equivalente)
    tiene_deuda_previsional     BOOLEAN NOT NULL DEFAULT false,
    -- En proceso de quiebra / insolvencia
    tiene_quiebra               BOOLEAN NOT NULL DEFAULT false,
    -- Restricción de folios o documentos
    tiene_restriccion_folios    BOOLEAN NOT NULL DEFAULT false,
    -- Tiene al menos una alerta calificada como grave por el organismo
    tiene_alerta_grave          BOOLEAN NOT NULL DEFAULT false,
    -- Resumen textual de la última alerta relevante (para mostrar en UI)
    ultima_alerta_texto         TEXT,

    -- ── Respuesta cruda completa (no perder ningún dato) ─────────────────
    -- Permite re-procesar sin re-consultar el organismo.
    -- Permite extraer nuevos campos sin ALTER TABLE.
    raw_response                JSONB NOT NULL DEFAULT '{}',

    -- ── Control de vigencia ──────────────────────────────────────────────
    -- La verificación tiene una vigencia (datos del SII cambian).
    -- vigente_hasta se calcula en la vista como consultado_en + 30 días.
    consultado_en               TIMESTAMPTZ NOT NULL DEFAULT now(),
    activo_registro             BOOLEAN NOT NULL DEFAULT true,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Una verificación activa por organización (UNIQUE parcial)
    UNIQUE (organizacion_id)
);

COMMENT ON TABLE core.organizacion_verificacion_tributaria IS
    'Estado tributario normalizado de una organización consultado a su organismo '
    'fiscal (SII/AFIP/SAT/DIAN). '
    'raw_response conserva la respuesta cruda para auditoría y re-procesamiento. '
    'vigente_hasta = consultado_en + 30 días — re-consultar si está vencida.';

COMMENT ON COLUMN core.organizacion_verificacion_tributaria.fuente IS
    'Organismo tributario origen: SII (Chile), AFIP (Argentina), SAT (México), DIAN (Colombia)';

COMMENT ON COLUMN core.organizacion_verificacion_tributaria.raw_response IS
    'Respuesta JSON completa del organismo. No alterar el esquema para nuevos campos: '
    'usar raw_response->''campo'' en queries o agregar columnas generadas.';

CREATE INDEX IF NOT EXISTS idx_vt_organizacion
    ON core.organizacion_verificacion_tributaria (organizacion_id)
    WHERE activo_registro = true;

CREATE INDEX IF NOT EXISTS idx_vt_fuente_pais
    ON core.organizacion_verificacion_tributaria (fuente, pais_id);

-- Índice GIN para queries sobre el JSON crudo (ej: raw_response @> '{"conTegi":true}')
CREATE INDEX IF NOT EXISTS idx_vt_raw_gin
    ON core.organizacion_verificacion_tributaria USING GIN (raw_response);

-- Trigger updated_at
CREATE OR REPLACE FUNCTION core.set_updated_at_verificacion_tributaria()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_updated_at_verificacion_tributaria
    ON core.organizacion_verificacion_tributaria;

CREATE TRIGGER trg_updated_at_verificacion_tributaria
    BEFORE UPDATE ON core.organizacion_verificacion_tributaria
    FOR EACH ROW EXECUTE FUNCTION core.set_updated_at_verificacion_tributaria();

-- ============================================================================
-- TABLA 2: organizacion_actividad_economica
-- Giros / actividades declaradas ante el organismo tributario
-- Basada en CIIU Rev.4 (estándar ONU — usado por SII, AFIP, DIAN, SAT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS core.organizacion_actividad_economica (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id     BIGINT  NOT NULL
                        REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,

    -- Fuente del dato (mismo organismo que la verificación tributaria)
    fuente              VARCHAR(20) NOT NULL,

    -- Código de actividad (CIIU o código local del organismo)
    codigo              VARCHAR(20) NOT NULL,

    -- Descripción tal como la entrega el organismo
    descripcion         VARCHAR(255),

    -- Clasificación tributaria (1=Primera categoría, 2=Segunda, etc.)
    categoria_tributaria SMALLINT,

    -- ¿La actividad está afecta a IVA? (S/N normalizado a boolean)
    afecto_iva          BOOLEAN,

    -- Fecha en que se declaró esta actividad
    fecha_inicio        DATE,

    -- ¿Es el giro principal? (el primer declarado suele serlo)
    es_principal        BOOLEAN NOT NULL DEFAULT false,

    activo              BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE core.organizacion_actividad_economica IS
    'Giros y actividades económicas declarados por la organización ante su organismo '
    'fiscal. Código basado en CIIU Rev.4 (estándar ONU) o código local equivalente. '
    'Una misma org puede tener múltiples actividades vigentes.';

COMMENT ON COLUMN core.organizacion_actividad_economica.codigo IS
    'Código CIIU Rev.4 o código local del organismo fiscal (ej: SII usa 6 dígitos).';

CREATE INDEX IF NOT EXISTS idx_ae_organizacion
    ON core.organizacion_actividad_economica (organizacion_id)
    WHERE activo = true;

CREATE INDEX IF NOT EXISTS idx_ae_codigo
    ON core.organizacion_actividad_economica (codigo);

-- ============================================================================
-- VISTA: v_verificacion_tributaria_vigente
-- Devuelve la verificación activa + resumen de actividades por organización.
-- Usada por el BFF para mostrar el perfil tributario en el wizard.
-- ============================================================================

CREATE OR REPLACE VIEW core.v_verificacion_tributaria_vigente AS
SELECT
    vt.id,
    vt.organizacion_id,
    vt.identificador_fiscal,
    vt.razon_social_oficial,
    vt.fuente,
    p.codigo                    AS pais_codigo,
    p.nombre                    AS pais_nombre,
    -- Estado
    vt.registrado,
    vt.activo,
    vt.cumple_obligacion,
    vt.primera_categoria,
    vt.emisor_dte,
    vt.tiene_factura_electronica,
    vt.fecha_inicio_actividades,
    -- Riesgo
    vt.tiene_deuda_previsional,
    vt.tiene_quiebra,
    vt.tiene_restriccion_folios,
    vt.tiene_alerta_grave,
    vt.ultima_alerta_texto,
    -- Vigencia (calculada aquí — TIMESTAMPTZ+INTERVAL no es IMMUTABLE)
    vt.consultado_en,
    (vt.consultado_en + INTERVAL '30 days')         AS vigente_hasta,
    (now() > vt.consultado_en + INTERVAL '30 days') AS requiere_actualizacion,
    -- Actividades (array JSON para consumo directo en el frontend)
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object(
            'codigo',       ae.codigo,
            'descripcion',  ae.descripcion,
            'afecto_iva',   ae.afecto_iva,
            'es_principal', ae.es_principal
        ) ORDER BY ae.es_principal DESC, ae.fecha_inicio)
        FROM core.organizacion_actividad_economica ae
        WHERE ae.organizacion_id = vt.organizacion_id
          AND ae.activo = true),
        '[]'::jsonb
    )                           AS actividades
FROM core.organizacion_verificacion_tributaria vt
JOIN core.pais p ON p.pais_id = vt.pais_id
WHERE vt.activo_registro = true;

-- ============================================================================
-- FIN 17_init_verificacion_tributaria.sql
-- ============================================================================
