-- =============================================================================
-- 18_init_solicitud_acceso.sql
-- Solicitudes de acceso de colaboradores a organizaciones
--
-- DEPENDE DE: 01_init_core.sql (core.organizacion, core.usuario)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. CATÁLOGO DE ROLES ORGANIZACIONALES
--    Roles que un colaborador puede tener dentro de una organización
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.organizacion_rol_catalog (
    rol_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo     VARCHAR(40) UNIQUE NOT NULL, -- ADMIN | OPERADOR | COLABORADOR | AUDITOR
    nombre     VARCHAR(80) NOT NULL,
    descripcion TEXT,
    activo     BOOLEAN DEFAULT true
);

INSERT INTO core.organizacion_rol_catalog (codigo, nombre, descripcion) VALUES
    ('ADMIN',       'Administrador',  'Control total: aprueba solicitudes, administra usuarios y configuración'),
    ('OPERADOR',    'Operador',       'Gestiona facturas, ofertas y operaciones del día a día'),
    ('COLABORADOR', 'Colaborador',    'Acceso de lectura y participación limitada'),
    ('AUDITOR',     'Auditor',        'Solo lectura, acceso a reportes y auditoría')
ON CONFLICT (codigo) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. MEMBRESÍA DE USUARIOS EN ORGANIZACIONES
--    Un usuario puede pertenecer a más de una organización con distintos roles
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.organizacion_miembro (
    miembro_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  BIGINT  NOT NULL
                     REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,
    usuario_uuid     UUID    NOT NULL
                     REFERENCES core.usuario(usuario_uuid) ON DELETE CASCADE,
    rol_codigo       VARCHAR(40) NOT NULL DEFAULT 'COLABORADOR'
                     REFERENCES core.organizacion_rol_catalog(codigo),
    activo           BOOLEAN NOT NULL DEFAULT true,
    incorporado_en   TIMESTAMPTZ NOT NULL DEFAULT now(),
    incorporado_por  UUID        REFERENCES core.usuario(usuario_uuid) ON DELETE SET NULL,

    UNIQUE (organizacion_id, usuario_uuid)
);

CREATE INDEX idx_org_miembro_org     ON core.organizacion_miembro (organizacion_id) WHERE activo = true;
CREATE INDEX idx_org_miembro_usuario ON core.organizacion_miembro (usuario_uuid)    WHERE activo = true;

-- ---------------------------------------------------------------------------
-- 3. SOLICITUDES DE ACCESO
--    Un colaborador solicita acceso a una organización.
--    Aparece en el panel del admin y opcionalmente se notifica por email.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS core.organizacion_solicitud_acceso (
    solicitud_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id BIGINT  NOT NULL
                    REFERENCES core.organizacion(organizacion_id) ON DELETE CASCADE,

    -- Quién solicita
    solicitante_uuid UUID   NOT NULL
                     REFERENCES core.usuario(usuario_uuid) ON DELETE CASCADE,

    -- Rol que solicita tener
    rol_solicitado  VARCHAR(40) NOT NULL DEFAULT 'COLABORADOR'
                    REFERENCES core.organizacion_rol_catalog(codigo),

    -- Mensaje opcional del solicitante ("Soy el ejecutivo de cuenta de...")
    mensaje         TEXT,

    -- Token único para aprobar/rechazar desde un link de email
    token           VARCHAR(64) UNIQUE NOT NULL
                    DEFAULT encode(gen_random_bytes(32), 'hex'),

    -- Estado del flujo
    estado          VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
                    CHECK (estado IN ('PENDIENTE','APROBADA','RECHAZADA','EXPIRADA','CANCELADA')),

    -- Quién resolvió (admin que aprobó/rechazó)
    resuelto_por    UUID REFERENCES core.usuario(usuario_uuid) ON DELETE SET NULL,
    resuelto_en     TIMESTAMPTZ,
    motivo_rechazo  TEXT,

    -- Timestamps
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    expira_en       TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '72 hours'),

    -- Una sola solicitud pendiente por usuario+org
    CONSTRAINT uq_solicitud_pendiente UNIQUE (organizacion_id, solicitante_uuid)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_solicitud_org     ON core.organizacion_solicitud_acceso (organizacion_id) WHERE estado = 'PENDIENTE';
CREATE INDEX idx_solicitud_usuario ON core.organizacion_solicitud_acceso (solicitante_uuid);
CREATE INDEX idx_solicitud_token   ON core.organizacion_solicitud_acceso (token) WHERE estado = 'PENDIENTE';

-- ---------------------------------------------------------------------------
-- 4. TRIGGER: marcar como EXPIRADA automáticamente al consultar
--    (No requiere cron; se evalúa en cada lectura de la vista)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION core.fn_marcar_solicitudes_expiradas()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE core.organizacion_solicitud_acceso
    SET    estado = 'EXPIRADA'
    WHERE  estado = 'PENDIENTE'
      AND  expira_en < now();
END;
$$;

-- ---------------------------------------------------------------------------
-- 5. VISTA PÚBLICA PARA EL PANEL DE ADMINISTRACIÓN
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW core.v_solicitudes_acceso AS
SELECT
    s.solicitud_id,
    s.organizacion_id,
    o.razon_social              AS organizacion_nombre,
    o.rut                       AS organizacion_rut,
    s.solicitante_uuid,
    c.nombres                   AS solicitante_nombre,
    c.apellido_paterno          AS solicitante_apellido,
    c.correo                     AS solicitante_email,
    s.rol_solicitado,
    s.mensaje,
    s.token,
    s.estado,
    s.resuelto_por,
    s.resuelto_en,
    s.motivo_rechazo,
    s.creado_en,
    s.expira_en,
    (now() > s.expira_en)       AS esta_expirada
FROM core.organizacion_solicitud_acceso s
JOIN core.organizacion o ON o.organizacion_id = s.organizacion_id
JOIN core.usuario      u ON u.usuario_uuid    = s.solicitante_uuid
JOIN core.contacto     c ON c.contacto_id     = u.contacto_id;

COMMENT ON TABLE  core.organizacion_solicitud_acceso IS
    'Solicitudes de colaboradores para unirse a una organización. '
    'El admin las ve en su panel y puede aprobar/rechazar. '
    'Opcionalmente se envía email con link de token.';

-- ---------------------------------------------------------------------------
-- 6. TRIGGER: al agregar miembro a grupo_trabajo → garantizar membresía org
--    Si el usuario aún no tiene entrada en organizacion_miembro para esa org,
--    se inserta automáticamente con rol COLABORADOR.
--    (grupo_trabajo.organizacion_id es UUID → se resuelve al BIGINT de organizacion)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION core.fn_sync_grupo_a_org_miembro()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_org_id BIGINT;
BEGIN
    -- Resolver organizacion_id BIGINT desde el UUID del grupo
    SELECT o.organizacion_id INTO v_org_id
    FROM   core.organizacion  o
    JOIN   core.grupo_trabajo gt ON gt.organizacion_id = o.organizacion_uuid
    WHERE  gt.grupo_id = NEW.grupo_id;

    IF v_org_id IS NULL THEN
        RETURN NEW;  -- grupo huérfano, no bloquear
    END IF;

    -- Garantizar membresía organizacional mínima (no sobreescribe rol superior)
    INSERT INTO core.organizacion_miembro (organizacion_id, usuario_uuid, rol_codigo, incorporado_por)
    VALUES (v_org_id, NEW.usuario_uuid, 'COLABORADOR', NULL)
    ON CONFLICT (organizacion_id, usuario_uuid) DO NOTHING;

    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_sync_grupo_a_org_miembro
AFTER INSERT ON core.grupo_miembro
FOR EACH ROW EXECUTE FUNCTION core.fn_sync_grupo_a_org_miembro();

-- ---------------------------------------------------------------------------
-- 7. FUNCIÓN: aprobar solicitud de acceso (transaccional)
--    Cambia estado a APROBADA + upsert en organizacion_miembro en una TX.
--    Uso: SELECT core.fn_aprobar_solicitud(42, 'uuid-del-admin');
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION core.fn_aprobar_solicitud(
    p_solicitud_id   BIGINT,
    p_aprobador_uuid UUID
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_sol core.organizacion_solicitud_acceso%ROWTYPE;
BEGIN
    -- Bloqueo de fila para evitar aprobaciones concurrentes
    SELECT * INTO v_sol
    FROM   core.organizacion_solicitud_acceso
    WHERE  solicitud_id = p_solicitud_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Solicitud % no encontrada', p_solicitud_id;
    END IF;

    IF v_sol.estado != 'PENDIENTE' THEN
        RAISE EXCEPTION 'La solicitud % ya fue procesada (estado: %)',
            p_solicitud_id, v_sol.estado;
    END IF;

    -- Marcar expirada si venció antes de que el admin la revisara
    IF v_sol.expira_en < now() THEN
        UPDATE core.organizacion_solicitud_acceso
        SET    estado = 'EXPIRADA'
        WHERE  solicitud_id = p_solicitud_id;
        RAISE EXCEPTION 'La solicitud % ha expirado', p_solicitud_id;
    END IF;

    -- Aprobar
    UPDATE core.organizacion_solicitud_acceso
    SET    estado       = 'APROBADA',
           resuelto_por = p_aprobador_uuid,
           resuelto_en  = now()
    WHERE  solicitud_id = p_solicitud_id;

    -- Upsert en organizacion_miembro con el rol solicitado
    -- Si ya existe (p.ej. venía de grupo_trabajo) actualiza al rol superior aprobado
    INSERT INTO core.organizacion_miembro (
        organizacion_id, usuario_uuid, rol_codigo, incorporado_por
    ) VALUES (
        v_sol.organizacion_id,
        v_sol.solicitante_uuid,
        v_sol.rol_solicitado,
        p_aprobador_uuid
    )
    ON CONFLICT (organizacion_id, usuario_uuid) DO UPDATE
        SET rol_codigo     = EXCLUDED.rol_codigo,
            incorporado_por = EXCLUDED.incorporado_por,
            incorporado_en  = now(),
            activo          = true;
END;
$$;

-- ---------------------------------------------------------------------------
-- 8. FUNCIÓN: rechazar solicitud de acceso
--    Uso: SELECT core.fn_rechazar_solicitud(42, 'uuid-del-admin', 'Motivo opcional');
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION core.fn_rechazar_solicitud(
    p_solicitud_id   BIGINT,
    p_aprobador_uuid UUID,
    p_motivo         TEXT DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE core.organizacion_solicitud_acceso
    SET    estado         = 'RECHAZADA',
           resuelto_por   = p_aprobador_uuid,
           resuelto_en    = now(),
           motivo_rechazo = p_motivo
    WHERE  solicitud_id = p_solicitud_id
      AND  estado       = 'PENDIENTE';

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Solicitud % no encontrada o ya procesada', p_solicitud_id;
    END IF;
END;
$$;
