CREATE TABLE "tipo_contacto" (
  "tipo_contacto_id" BIGINT PRIMARY KEY,
  "nombre" VARCHAR,
  "descripcion" VARCHAR
);

CREATE TABLE "contacto" (
  "contacto_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR,
  "direccion" VARCHAR,
  "celular" VARCHAR,
  "correo" VARCHAR,
  "redes_sociales" VARCHAR,
  "url" VARCHAR,
  "imagen_base64" TEXT,
  "tipo_contacto_id" BIGINT
);

CREATE TABLE "organizacion" (
  "organizacion_id" BIGINT PRIMARY KEY,
  "razon_social" VARCHAR,
  "rut" VARCHAR,
  "dv" char(1),
  "giro" VARCHAR,
  "logo_base64" TEXT,
  "contacto_id" BIGINT
);

CREATE TABLE "cuenta_bancaria" (
  "cuenta_id" BIGINT PRIMARY KEY,
  "nombre_titular" VARCHAR,
  "banco" VARCHAR,
  "numero" VARCHAR,
  "correo_contacto" VARCHAR,
  "rut_titular" VARCHAR,
  "organizacion_id" BIGINT
);

CREATE TABLE "sistema" (
  "sistema_id" BIGINT PRIMARY KEY,
  "nombre" VARCHAR,
  "descripcion" VARCHAR,
  "activo" BOOLEAN
);

CREATE TABLE "modulo" (
  "modulo_id" BIGINT PRIMARY KEY,
  "nombre" VARCHAR,
  "descripcion" VARCHAR,
  "activo" BOOLEAN,
  "sistema_id" BIGINT
);

CREATE TABLE "organizacion_sistema" (
  "organizacion_id" BIGINT NOT NULL,
  "sistema_id" BIGINT NOT NULL,
  PRIMARY KEY ("organizacion_id", "sistema_id")
);

CREATE TABLE "rol" (
  "rol_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR,
  "descripcion" VARCHAR
);

CREATE TABLE "permiso" (
  "permiso_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR,
  "descripcion" VARCHAR,
  "codigo" VARCHAR,
  "activo" BOOLEAN DEFAULT true
);

CREATE TABLE "modulo_permiso" (
  "modulo_id" BIGINT NOT NULL,
  "permiso_id" BIGINT NOT NULL,
  PRIMARY KEY ("modulo_id", "permiso_id")
);

CREATE TABLE "rol_modulo_permiso" (
  "rol_id" BIGINT NOT NULL,
  "modulo_id" BIGINT NOT NULL,
  "permiso_id" BIGINT NOT NULL,
  PRIMARY KEY ("rol_id", "modulo_id", "permiso_id")
);

CREATE TABLE "usuario" (
  "usuario_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR,
  "password_hash" VARCHAR,
  "fecha_creacion" DATE,
  "activo" BOOLEAN DEFAULT true,
  "fecha_actualizacion" DATE,
  "contacto_id" BIGINT
);

CREATE TABLE "usuario_rol" (
  "usuario_id" BIGINT NOT NULL,
  "rol_id" BIGINT NOT NULL,
  PRIMARY KEY ("usuario_id", "rol_id")
);

CREATE TABLE "organizacion_contacto" (
  "contacto_id" BIGINT NOT NULL,
  "organizacion_id" BIGINT NOT NULL,
  PRIMARY KEY ("contacto_id", "organizacion_id")
);

ALTER TABLE "contacto" ADD FOREIGN KEY ("tipo_contacto_id") REFERENCES "tipo_contacto" ("tipo_contacto_id");

ALTER TABLE "organizacion_contacto" ADD FOREIGN KEY ("contacto_id") REFERENCES "contacto" ("contacto_id");

ALTER TABLE "organizacion_contacto" ADD FOREIGN KEY ("organizacion_id") REFERENCES "organizacion" ("organizacion_id");

ALTER TABLE "cuenta_bancaria" ADD FOREIGN KEY ("organizacion_id") REFERENCES "organizacion" ("organizacion_id");

ALTER TABLE "modulo" ADD FOREIGN KEY ("sistema_id") REFERENCES "sistema" ("sistema_id");

ALTER TABLE "organizacion_sistema" ADD FOREIGN KEY ("organizacion_id") REFERENCES "organizacion" ("organizacion_id");

ALTER TABLE "organizacion_sistema" ADD FOREIGN KEY ("sistema_id") REFERENCES "sistema" ("sistema_id");

ALTER TABLE "modulo_permiso" ADD FOREIGN KEY ("modulo_id") REFERENCES "modulo" ("modulo_id");

ALTER TABLE "modulo_permiso" ADD FOREIGN KEY ("permiso_id") REFERENCES "permiso" ("permiso_id");

ALTER TABLE "rol_modulo_permiso" ADD FOREIGN KEY ("rol_id") REFERENCES "rol" ("rol_id");

ALTER TABLE "rol_modulo_permiso" ADD FOREIGN KEY ("modulo_id") REFERENCES "modulo" ("modulo_id");

ALTER TABLE "rol_modulo_permiso" ADD FOREIGN KEY ("permiso_id") REFERENCES "permiso" ("permiso_id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("contacto_id") REFERENCES "contacto" ("contacto_id");

ALTER TABLE "usuario_rol" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id");

ALTER TABLE "usuario_rol" ADD FOREIGN KEY ("rol_id") REFERENCES "rol" ("rol_id");
