CREATE TABLE "item" (
  "item_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "item_nombre" VARCHAR,
  "item_stock" Bigint,
  "item_sublimable" Boolean,
  "item_img_base64" Character varying,
  "marca_id" Bigint,
  "tipo_id" Bigint,
  "cat_id" Bigint,
  "sub_cat_id" Bigint,
  "size_id" Bigint,
  "org_id" Bigint
);

CREATE TABLE "marca" (
  "marca_id" Bigint PRIMARY KEY NOT NULL,
  "marca_nombre" VARCHAR,
  "marca_desc" VARCHAR
);

CREATE TABLE "tipo" (
  "tipo_id" Bigint PRIMARY KEY NOT NULL,
  "tipo_nombre" VARCHAR,
  "tipo_desc" VARCHAR
);

CREATE TABLE "categoria" (
  "cat_id" Bigint PRIMARY KEY NOT NULL,
  "cat_nombre" VARCHAR,
  "cat_desc" VARCHAR,
  "tipo_id" Bigint
);

CREATE TABLE "sub_categoria" (
  "sub_cat_id" Bigint PRIMARY KEY NOT NULL,
  "sub_cat_nombre" VARCHAR,
  "sub_cat_desc" VARCHAR,
  "cat_id" Bigint
);

CREATE TABLE "size_item" (
  "size_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "size" Character varying,
  "size_orden" Bigint
);

CREATE TABLE "size_tipo" (
  "size_id" Bigint NOT NULL,
  "tipo_id" Bigint NOT NULL,
  PRIMARY KEY ("size_id", "tipo_id")
);

CREATE TABLE "ubicacion" (
  "id" BIGSERIAL PRIMARY KEY,
  "nombre" TEXT NOT NULL,
  "descripcion" TEXT,
  "tipo" TEXT,
  "pasillo" TEXT,
  "rack" TEXT,
  "estante" TEXT
);

CREATE TABLE "stock" (
  "item_id" BIGINT NOT NULL,
  "ubicacion_id" BIGINT NOT NULL,
  "cantidad" BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY ("item_id", "ubicacion_id")
);

CREATE TABLE "tipo_movimiento" (
  "id" BIGSERIAL PRIMARY KEY,
  "nombre" TEXT UNIQUE NOT NULL,
  "afecta_stock" BOOLEAN NOT NULL
);

CREATE TABLE "usuario" (
  "usuario_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "usu_username" Character varying,
  "usu_password" Character varying,
  "usu_creacion" Date,
  "usu_activo" Boolean DEFAULT true,
  "usu_update" Date,
  "contacto_id" Bigint,
  "rol" Bigint
);

CREATE TABLE "movimiento" (
  "id" BIGSERIAL PRIMARY KEY,
  "item_id" BIGINT NOT NULL,
  "tipo_movimiento_id" BIGINT NOT NULL,
  "cantidad" BIGINT NOT NULL,
  "fecha" "TIMESTAMPTZ" NOT NULL DEFAULT (now()),
  "ubicacion_origen_id" BIGINT,
  "ubicacion_destino_id" BIGINT,
  "motivo" TEXT,
  "usuario_id" BIGINT
);

CREATE TABLE "inventario_fisico" (
  "id" BIGSERIAL PRIMARY KEY,
  "fecha" DATE NOT NULL DEFAULT (now()),
  "observaciones" TEXT,
  "usuario_id" BIGINT
);

CREATE TABLE "ajuste_inventario" (
  "id" BIGSERIAL PRIMARY KEY,
  "inventario_fisico_id" BIGINT NOT NULL,
  "item_id" BIGINT NOT NULL,
  "ubicacion_id" BIGINT NOT NULL,
  "stock_actual" BIGINT NOT NULL,
  "stock_fisico" BIGINT NOT NULL,
  "diferencia" BIGINT
);

CREATE INDEX "idx_marca" ON "item" ("marca_id");

CREATE INDEX "idx_tipo_itm" ON "item" ("tipo_id");

CREATE INDEX "idx_cat" ON "item" ("cat_id");

CREATE INDEX "idx_subcat" ON "item" ("sub_cat_id");

CREATE INDEX "idx_size" ON "item" ("size_id");

CREATE INDEX "ix_relationship4" ON "item" ("org_id");

CREATE INDEX "idx_tipo" ON "categoria" ("tipo_id");

CREATE INDEX "idx_cat_sub" ON "sub_categoria" ("cat_id");

CREATE INDEX "idx_stock_item" ON "stock" ("item_id");

CREATE INDEX "idx_stock_ubicacion" ON "stock" ("ubicacion_id");

CREATE INDEX "indx_contacto" ON "usuario" ("contacto_id");

CREATE INDEX "indx_rol" ON "usuario" ("rol");

CREATE INDEX "idx_movimiento_item" ON "movimiento" ("item_id");

CREATE INDEX "idx_movimiento_fecha" ON "movimiento" ("fecha");

CREATE INDEX "idx_movimiento_usuario" ON "movimiento" ("usuario_id");

CREATE INDEX "idx_ajuste_item" ON "ajuste_inventario" ("item_id");

ALTER TABLE "stock" ADD FOREIGN KEY ("ubicacion_id") REFERENCES "ubicacion" ("id") ON DELETE CASCADE;

ALTER TABLE "movimiento" ADD FOREIGN KEY ("tipo_movimiento_id") REFERENCES "tipo_movimiento" ("id");

ALTER TABLE "movimiento" ADD FOREIGN KEY ("ubicacion_origen_id") REFERENCES "ubicacion" ("id");

ALTER TABLE "movimiento" ADD FOREIGN KEY ("ubicacion_destino_id") REFERENCES "ubicacion" ("id");

ALTER TABLE "movimiento" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") ON DELETE SET NULL;

ALTER TABLE "inventario_fisico" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id") ON DELETE SET NULL;

ALTER TABLE "ajuste_inventario" ADD FOREIGN KEY ("inventario_fisico_id") REFERENCES "inventario_fisico" ("id") ON DELETE CASCADE;

ALTER TABLE "ajuste_inventario" ADD FOREIGN KEY ("ubicacion_id") REFERENCES "ubicacion" ("id");

ALTER TABLE "item" ADD CONSTRAINT "marca=item" FOREIGN KEY ("marca_id") REFERENCES "marca" ("marca_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "item" ADD CONSTRAINT "tipo=item" FOREIGN KEY ("tipo_id") REFERENCES "tipo" ("tipo_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "item" ADD CONSTRAINT "cat=item" FOREIGN KEY ("cat_id") REFERENCES "categoria" ("cat_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "item" ADD CONSTRAINT "sub_cat=item" FOREIGN KEY ("sub_cat_id") REFERENCES "sub_categoria" ("sub_cat_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "categoria" ADD CONSTRAINT "tipo=categorias" FOREIGN KEY ("tipo_id") REFERENCES "tipo" ("tipo_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "sub_categoria" ADD CONSTRAINT "categorias=subcategorias" FOREIGN KEY ("cat_id") REFERENCES "categoria" ("cat_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "item" ADD CONSTRAINT "size=item" FOREIGN KEY ("size_id") REFERENCES "size_item" ("size_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "size_tipo" ADD CONSTRAINT "size=tipos" FOREIGN KEY ("size_id") REFERENCES "size_item" ("size_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "size_tipo" ADD CONSTRAINT "tipo=size" FOREIGN KEY ("tipo_id") REFERENCES "tipo" ("tipo_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "movimiento" ADD CONSTRAINT "item>movimiento" FOREIGN KEY ("item_id") REFERENCES "item" ("item_id");

ALTER TABLE "stock" ADD CONSTRAINT "item<stock" FOREIGN KEY ("item_id") REFERENCES "item" ("item_id");

ALTER TABLE "ajuste_inventario" ADD CONSTRAINT "item<ajuste_inventario" FOREIGN KEY ("item_id") REFERENCES "item" ("item_id");
